################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/core/mappers/mapper_0.c \
../src/core/mappers/mapper_105.c \
../src/core/mappers/mapper_114.c \
../src/core/mappers/mapper_116.c \
../src/core/mappers/mapper_120.c \
../src/core/mappers/mapper_121.c \
../src/core/mappers/mapper_156.c \
../src/core/mappers/mapper_163.c \
../src/core/mappers/mapper_164.c \
../src/core/mappers/mapper_176.c \
../src/core/mappers/mapper_178.c \
../src/core/mappers/mapper_182.c \
../src/core/mappers/mapper_183.c \
../src/core/mappers/mapper_186.c \
../src/core/mappers/mapper_200.c \
../src/core/mappers/mapper_201.c \
../src/core/mappers/mapper_202.c \
../src/core/mappers/mapper_203.c \
../src/core/mappers/mapper_204.c \
../src/core/mappers/mapper_205.c \
../src/core/mappers/mapper_208.c \
../src/core/mappers/mapper_212.c \
../src/core/mappers/mapper_213.c \
../src/core/mappers/mapper_214.c \
../src/core/mappers/mapper_215.c \
../src/core/mappers/mapper_217.c \
../src/core/mappers/mapper_219.c \
../src/core/mappers/mapper_221.c \
../src/core/mappers/mapper_222.c \
../src/core/mappers/mapper_225.c \
../src/core/mappers/mapper_226.c \
../src/core/mappers/mapper_227.c \
../src/core/mappers/mapper_229.c \
../src/core/mappers/mapper_230.c \
../src/core/mappers/mapper_231.c \
../src/core/mappers/mapper_233.c \
../src/core/mappers/mapper_235.c \
../src/core/mappers/mapper_240.c \
../src/core/mappers/mapper_241.c \
../src/core/mappers/mapper_242.c \
../src/core/mappers/mapper_244.c \
../src/core/mappers/mapper_246.c \
../src/core/mappers/mapper_249.c \
../src/core/mappers/mapper_28.c \
../src/core/mappers/mapper_31.c \
../src/core/mappers/mapper_37.c \
../src/core/mappers/mapper_42.c \
../src/core/mappers/mapper_44.c \
../src/core/mappers/mapper_45.c \
../src/core/mappers/mapper_46.c \
../src/core/mappers/mapper_47.c \
../src/core/mappers/mapper_49.c \
../src/core/mappers/mapper_50.c \
../src/core/mappers/mapper_51.c \
../src/core/mappers/mapper_52.c \
../src/core/mappers/mapper_53.c \
../src/core/mappers/mapper_57.c \
../src/core/mappers/mapper_58.c \
../src/core/mappers/mapper_60.c \
../src/core/mappers/mapper_61.c \
../src/core/mappers/mapper_62.c \
../src/core/mappers/mapper_74x138x161.c \
../src/core/mappers/mapper_74x161x161x32.c \
../src/core/mappers/mapper_83.c \
../src/core/mappers/mapper_90_209_211.c \
../src/core/mappers/mapper_91.c \
../src/core/mappers/mapper_A65AS.c \
../src/core/mappers/mapper_Active.c \
../src/core/mappers/mapper_Agci.c \
../src/core/mappers/mapper_Ave.c \
../src/core/mappers/mapper_AxROM.c \
../src/core/mappers/mapper_BMCFK23C.c \
../src/core/mappers/mapper_Bandai.c \
../src/core/mappers/mapper_BxROM.c \
../src/core/mappers/mapper_CNROM.c \
../src/core/mappers/mapper_CPROM.c \
../src/core/mappers/mapper_Caltron.c \
../src/core/mappers/mapper_Camerica.c \
../src/core/mappers/mapper_ColorDreams.c \
../src/core/mappers/mapper_FDS.c \
../src/core/mappers/mapper_Futuremedia.c \
../src/core/mappers/mapper_GameGenie.c \
../src/core/mappers/mapper_GxROM.c \
../src/core/mappers/mapper_Hen.c \
../src/core/mappers/mapper_Hes.c \
../src/core/mappers/mapper_Irem.c \
../src/core/mappers/mapper_Jaleco.c \
../src/core/mappers/mapper_Kaiser.c \
../src/core/mappers/mapper_Kasing.c \
../src/core/mappers/mapper_MMC1.c \
../src/core/mappers/mapper_MMC2andMMC4.c \
../src/core/mappers/mapper_MMC3.c \
../src/core/mappers/mapper_MMC5.c \
../src/core/mappers/mapper_Magic.c \
../src/core/mappers/mapper_Malee.c \
../src/core/mappers/mapper_Namco.c \
../src/core/mappers/mapper_Ntdec.c \
../src/core/mappers/mapper_Rcm.c \
../src/core/mappers/mapper_Rex.c \
../src/core/mappers/mapper_Sachen.c \
../src/core/mappers/mapper_Sunsoft.c \
../src/core/mappers/mapper_Taito.c \
../src/core/mappers/mapper_Tengen.c \
../src/core/mappers/mapper_TxROM.c \
../src/core/mappers/mapper_Txc.c \
../src/core/mappers/mapper_UxROM.c \
../src/core/mappers/mapper_VRC1.c \
../src/core/mappers/mapper_VRC2.c \
../src/core/mappers/mapper_VRC3.c \
../src/core/mappers/mapper_VRC4.c \
../src/core/mappers/mapper_VRC6.c \
../src/core/mappers/mapper_VRC7.c \
../src/core/mappers/mapper_VRC7_snd.c \
../src/core/mappers/mapper_Vs.c \
../src/core/mappers/mapper_Waixing.c \
../src/core/mappers/mapper_Whirlwind.c 

OBJS += \
./src/core/mappers/mapper_0.o \
./src/core/mappers/mapper_105.o \
./src/core/mappers/mapper_114.o \
./src/core/mappers/mapper_116.o \
./src/core/mappers/mapper_120.o \
./src/core/mappers/mapper_121.o \
./src/core/mappers/mapper_156.o \
./src/core/mappers/mapper_163.o \
./src/core/mappers/mapper_164.o \
./src/core/mappers/mapper_176.o \
./src/core/mappers/mapper_178.o \
./src/core/mappers/mapper_182.o \
./src/core/mappers/mapper_183.o \
./src/core/mappers/mapper_186.o \
./src/core/mappers/mapper_200.o \
./src/core/mappers/mapper_201.o \
./src/core/mappers/mapper_202.o \
./src/core/mappers/mapper_203.o \
./src/core/mappers/mapper_204.o \
./src/core/mappers/mapper_205.o \
./src/core/mappers/mapper_208.o \
./src/core/mappers/mapper_212.o \
./src/core/mappers/mapper_213.o \
./src/core/mappers/mapper_214.o \
./src/core/mappers/mapper_215.o \
./src/core/mappers/mapper_217.o \
./src/core/mappers/mapper_219.o \
./src/core/mappers/mapper_221.o \
./src/core/mappers/mapper_222.o \
./src/core/mappers/mapper_225.o \
./src/core/mappers/mapper_226.o \
./src/core/mappers/mapper_227.o \
./src/core/mappers/mapper_229.o \
./src/core/mappers/mapper_230.o \
./src/core/mappers/mapper_231.o \
./src/core/mappers/mapper_233.o \
./src/core/mappers/mapper_235.o \
./src/core/mappers/mapper_240.o \
./src/core/mappers/mapper_241.o \
./src/core/mappers/mapper_242.o \
./src/core/mappers/mapper_244.o \
./src/core/mappers/mapper_246.o \
./src/core/mappers/mapper_249.o \
./src/core/mappers/mapper_28.o \
./src/core/mappers/mapper_31.o \
./src/core/mappers/mapper_37.o \
./src/core/mappers/mapper_42.o \
./src/core/mappers/mapper_44.o \
./src/core/mappers/mapper_45.o \
./src/core/mappers/mapper_46.o \
./src/core/mappers/mapper_47.o \
./src/core/mappers/mapper_49.o \
./src/core/mappers/mapper_50.o \
./src/core/mappers/mapper_51.o \
./src/core/mappers/mapper_52.o \
./src/core/mappers/mapper_53.o \
./src/core/mappers/mapper_57.o \
./src/core/mappers/mapper_58.o \
./src/core/mappers/mapper_60.o \
./src/core/mappers/mapper_61.o \
./src/core/mappers/mapper_62.o \
./src/core/mappers/mapper_74x138x161.o \
./src/core/mappers/mapper_74x161x161x32.o \
./src/core/mappers/mapper_83.o \
./src/core/mappers/mapper_90_209_211.o \
./src/core/mappers/mapper_91.o \
./src/core/mappers/mapper_A65AS.o \
./src/core/mappers/mapper_Active.o \
./src/core/mappers/mapper_Agci.o \
./src/core/mappers/mapper_Ave.o \
./src/core/mappers/mapper_AxROM.o \
./src/core/mappers/mapper_BMCFK23C.o \
./src/core/mappers/mapper_Bandai.o \
./src/core/mappers/mapper_BxROM.o \
./src/core/mappers/mapper_CNROM.o \
./src/core/mappers/mapper_CPROM.o \
./src/core/mappers/mapper_Caltron.o \
./src/core/mappers/mapper_Camerica.o \
./src/core/mappers/mapper_ColorDreams.o \
./src/core/mappers/mapper_FDS.o \
./src/core/mappers/mapper_Futuremedia.o \
./src/core/mappers/mapper_GameGenie.o \
./src/core/mappers/mapper_GxROM.o \
./src/core/mappers/mapper_Hen.o \
./src/core/mappers/mapper_Hes.o \
./src/core/mappers/mapper_Irem.o \
./src/core/mappers/mapper_Jaleco.o \
./src/core/mappers/mapper_Kaiser.o \
./src/core/mappers/mapper_Kasing.o \
./src/core/mappers/mapper_MMC1.o \
./src/core/mappers/mapper_MMC2andMMC4.o \
./src/core/mappers/mapper_MMC3.o \
./src/core/mappers/mapper_MMC5.o \
./src/core/mappers/mapper_Magic.o \
./src/core/mappers/mapper_Malee.o \
./src/core/mappers/mapper_Namco.o \
./src/core/mappers/mapper_Ntdec.o \
./src/core/mappers/mapper_Rcm.o \
./src/core/mappers/mapper_Rex.o \
./src/core/mappers/mapper_Sachen.o \
./src/core/mappers/mapper_Sunsoft.o \
./src/core/mappers/mapper_Taito.o \
./src/core/mappers/mapper_Tengen.o \
./src/core/mappers/mapper_TxROM.o \
./src/core/mappers/mapper_Txc.o \
./src/core/mappers/mapper_UxROM.o \
./src/core/mappers/mapper_VRC1.o \
./src/core/mappers/mapper_VRC2.o \
./src/core/mappers/mapper_VRC3.o \
./src/core/mappers/mapper_VRC4.o \
./src/core/mappers/mapper_VRC6.o \
./src/core/mappers/mapper_VRC7.o \
./src/core/mappers/mapper_VRC7_snd.o \
./src/core/mappers/mapper_Vs.o \
./src/core/mappers/mapper_Waixing.o \
./src/core/mappers/mapper_Whirlwind.o 

C_DEPS += \
./src/core/mappers/mapper_0.d \
./src/core/mappers/mapper_105.d \
./src/core/mappers/mapper_114.d \
./src/core/mappers/mapper_116.d \
./src/core/mappers/mapper_120.d \
./src/core/mappers/mapper_121.d \
./src/core/mappers/mapper_156.d \
./src/core/mappers/mapper_163.d \
./src/core/mappers/mapper_164.d \
./src/core/mappers/mapper_176.d \
./src/core/mappers/mapper_178.d \
./src/core/mappers/mapper_182.d \
./src/core/mappers/mapper_183.d \
./src/core/mappers/mapper_186.d \
./src/core/mappers/mapper_200.d \
./src/core/mappers/mapper_201.d \
./src/core/mappers/mapper_202.d \
./src/core/mappers/mapper_203.d \
./src/core/mappers/mapper_204.d \
./src/core/mappers/mapper_205.d \
./src/core/mappers/mapper_208.d \
./src/core/mappers/mapper_212.d \
./src/core/mappers/mapper_213.d \
./src/core/mappers/mapper_214.d \
./src/core/mappers/mapper_215.d \
./src/core/mappers/mapper_217.d \
./src/core/mappers/mapper_219.d \
./src/core/mappers/mapper_221.d \
./src/core/mappers/mapper_222.d \
./src/core/mappers/mapper_225.d \
./src/core/mappers/mapper_226.d \
./src/core/mappers/mapper_227.d \
./src/core/mappers/mapper_229.d \
./src/core/mappers/mapper_230.d \
./src/core/mappers/mapper_231.d \
./src/core/mappers/mapper_233.d \
./src/core/mappers/mapper_235.d \
./src/core/mappers/mapper_240.d \
./src/core/mappers/mapper_241.d \
./src/core/mappers/mapper_242.d \
./src/core/mappers/mapper_244.d \
./src/core/mappers/mapper_246.d \
./src/core/mappers/mapper_249.d \
./src/core/mappers/mapper_28.d \
./src/core/mappers/mapper_31.d \
./src/core/mappers/mapper_37.d \
./src/core/mappers/mapper_42.d \
./src/core/mappers/mapper_44.d \
./src/core/mappers/mapper_45.d \
./src/core/mappers/mapper_46.d \
./src/core/mappers/mapper_47.d \
./src/core/mappers/mapper_49.d \
./src/core/mappers/mapper_50.d \
./src/core/mappers/mapper_51.d \
./src/core/mappers/mapper_52.d \
./src/core/mappers/mapper_53.d \
./src/core/mappers/mapper_57.d \
./src/core/mappers/mapper_58.d \
./src/core/mappers/mapper_60.d \
./src/core/mappers/mapper_61.d \
./src/core/mappers/mapper_62.d \
./src/core/mappers/mapper_74x138x161.d \
./src/core/mappers/mapper_74x161x161x32.d \
./src/core/mappers/mapper_83.d \
./src/core/mappers/mapper_90_209_211.d \
./src/core/mappers/mapper_91.d \
./src/core/mappers/mapper_A65AS.d \
./src/core/mappers/mapper_Active.d \
./src/core/mappers/mapper_Agci.d \
./src/core/mappers/mapper_Ave.d \
./src/core/mappers/mapper_AxROM.d \
./src/core/mappers/mapper_BMCFK23C.d \
./src/core/mappers/mapper_Bandai.d \
./src/core/mappers/mapper_BxROM.d \
./src/core/mappers/mapper_CNROM.d \
./src/core/mappers/mapper_CPROM.d \
./src/core/mappers/mapper_Caltron.d \
./src/core/mappers/mapper_Camerica.d \
./src/core/mappers/mapper_ColorDreams.d \
./src/core/mappers/mapper_FDS.d \
./src/core/mappers/mapper_Futuremedia.d \
./src/core/mappers/mapper_GameGenie.d \
./src/core/mappers/mapper_GxROM.d \
./src/core/mappers/mapper_Hen.d \
./src/core/mappers/mapper_Hes.d \
./src/core/mappers/mapper_Irem.d \
./src/core/mappers/mapper_Jaleco.d \
./src/core/mappers/mapper_Kaiser.d \
./src/core/mappers/mapper_Kasing.d \
./src/core/mappers/mapper_MMC1.d \
./src/core/mappers/mapper_MMC2andMMC4.d \
./src/core/mappers/mapper_MMC3.d \
./src/core/mappers/mapper_MMC5.d \
./src/core/mappers/mapper_Magic.d \
./src/core/mappers/mapper_Malee.d \
./src/core/mappers/mapper_Namco.d \
./src/core/mappers/mapper_Ntdec.d \
./src/core/mappers/mapper_Rcm.d \
./src/core/mappers/mapper_Rex.d \
./src/core/mappers/mapper_Sachen.d \
./src/core/mappers/mapper_Sunsoft.d \
./src/core/mappers/mapper_Taito.d \
./src/core/mappers/mapper_Tengen.d \
./src/core/mappers/mapper_TxROM.d \
./src/core/mappers/mapper_Txc.d \
./src/core/mappers/mapper_UxROM.d \
./src/core/mappers/mapper_VRC1.d \
./src/core/mappers/mapper_VRC2.d \
./src/core/mappers/mapper_VRC3.d \
./src/core/mappers/mapper_VRC4.d \
./src/core/mappers/mapper_VRC6.d \
./src/core/mappers/mapper_VRC7.d \
./src/core/mappers/mapper_VRC7_snd.d \
./src/core/mappers/mapper_Vs.d \
./src/core/mappers/mapper_Waixing.d \
./src/core/mappers/mapper_Whirlwind.d 


# Each subdirectory must supply rules for building sources it contributes
src/core/mappers/%.o: ../src/core/mappers/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Compiler'
	x86_64-w64-mingw32-gcc -DSDL -DGLEW_STATIC -I/home/fhorse/sviluppo/personale/punes/src -I/home/fhorse/sviluppo/personale/punes/src/core -I/home/fhorse/sviluppo/personale/punes/src/gui -I/home/fhorse/sviluppo/personale/punes/src/gui/windows -I/home/fhorse/sviluppo/personale/punes/src/video/sdl -I/usr/x86_64-w64-mingw32/usr/include/SDL -I/usr/x86_64-w64-mingw32/usr/include/qt4 -I/home/fhorse/sviluppo/personale/punes/misc/DXSDK/Include -I/home/fhorse/sviluppo/personale/punes/misc/DXSDK/vc10/include -O3 -Wall -ffast-math -mmmx -msse -msse2 -msse3 -mfpmath=sse -c -fmessage-length=0 -finline-functions -Winline -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


