
OPTFLAGS=-O

# don't use -DNDEBUG in order to use MacOSX wxWidgets

ALLFLAGS=-m64 ${OPTFLAGS}  \
	-DENV_MACOSX \
    	-D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE \
	-D_REENTRANT -DENV_UNIX \
	$(LOCAL_FLAGS)

CXX=/Developer/usr/bin/llvm-g++ $(ALLFLAGS)
CC=/Developer/usr/bin/llvm-gcc $(ALLFLAGS)
LINK_SHARED=-bundle

LOCAL_LIBS=-framework CoreFoundation
LOCAL_LIBS_DLL=$(LOCAL_LIBS)

OBJ_CRC32=$(OBJ_CRC32_C)

