#
# makefile for Linux (x86, PPC, alpha ...)
#

# OPTFLAGS=-fast -msse3 -s
OPTFLAGS=-O2 -msse2 -s -Wcheck -fstack-security-check

ALLFLAGS=${OPTFLAGS} \
    	-D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE \
	-DNDEBUG -D_REENTRANT -DENV_UNIX \
	-D_7ZIP_LARGE_PAGES \
	$(LOCAL_FLAGS)

CXX=icpc -i-static $(ALLFLAGS)
CC=icc $(ALLFLAGS)
CC_SHARED=-fPIC
LINK_SHARED=-fPIC -shared
ASM=nasm -f elf

LOCAL_LIBS=-lpthread
LOCAL_LIBS_DLL=$(LOCAL_LIBS) -ldl

CPU=x86
OBJ_CRC32=$(OBJ_CRC32_x86)

