{
"void main_vertex\n"
"(\n"
"	float4 position : POSITION,\n"
"	float4 color    : COLOR,\n"
"	float2 texCoord : TEXCOORD0,\n"
"\n"
"   uniform float4x4 modelViewProj,\n"
"\n"
"	out float4 oPosition : POSITION,\n"
"	out float2 otexCoord : TEXCOORD\n"
")\n"
"{\n"
"	oPosition = mul(modelViewProj, position);\n"
"	otexCoord = texCoord;\n"
"}\n"
"\n"
"struct input\n"
"{\n"
"   float2 video_size;\n"
"   float2 texture_size;\n"
"   float2 output_size;\n"
"   float  frame_count;\n"
"   float  frame_direction;\n"
"   float  frame_rotation;\n"
"};\n"
"\n"
#include "blur_params.inc"
"\n"
"#define kernel(x) exp(-GLOW_FALLOFF * (x) * (x))\n"
"\n"
"float4 main_fragment(float2 tex : TEXCOORD0, uniform sampler2D s0 : TEXUNIT0, uniform input IN) : COLOR\n"
"{\n"
"   float3 col = float3(0.0);\n"
"   float dx = 4.0 / IN.texture_size.x; // Mipmapped\n"
"\n"
"   float k_total = 0.0;\n"
"   for (int i = -TAPS; i <= TAPS; i++)\n"
"   {\n"
"      float k = kernel(i);\n"
"      k_total += k;\n"
"      col += k * tex2D(s0, tex + float2(float(i) * dx, 0.0)).rgb;\n"
"   }\n"
"   return float4(col / k_total, 1.0);\n"
"}\n"
"\n"
},
