{
"void main_vertex\n"
"(\n"
"	float4 position : POSITION,\n"
"	float4 color    : COLOR,\n"
"	float2 texCoord : TEXCOORD0,\n"
"\n"
"   uniform float4x4 modelViewProj,\n"
"\n"
"	out float4 oPosition : POSITION,\n"
"	out float2 otexCoord : TEXCOORD\n"
")\n"
"{\n"
"	oPosition = mul(modelViewProj, position);\n"
"	otexCoord = texCoord;\n"
"}\n"
"\n"
"struct input\n"
"{\n"
"   float2 video_size;\n"
"   float2 texture_size;\n"
"   float2 output_size;\n"
"   float  frame_count;\n"
"   float  frame_direction;\n"
"   float  frame_rotation;\n"
"};\n"
"\n"
"#pragma parameter GAMMA \"Input Gamma\" 2.4 2.0 2.6 0.02\n"
"#ifdef PARAMETER_UNIFORM\n"
"uniform float GAMMA;\n"
"#else\n"
"#define GAMMA 2.4\n"
"#endif\n"
"\n"
"float4 main_fragment(float2 tex : TEXCOORD0, uniform sampler2D s0 : TEXUNIT0, uniform input IN) : COLOR\n"
"{\n"
"   float3 color = tex2D(s0, tex).rgb;\n"
"   return float4(pow(color, GAMMA), 1.0);\n"
"}\n"
"\n"
},
