SRCS=myGetTickCount.cpp \
 mySplitCommandLine.cpp \
 myAddExeFlag.cpp \
 test_emul.cpp \
 wine_date_and_time.cpp \
 wine_GetXXXDefaultLangID.cpp \
 ../Common/MyVector.cpp \
 ../Common/MyString.cpp \
 ../Common/MyWindows.cpp

mySplitCommandLine.o : mySplitCommandLine.cpp
	$(CXX) $(CXXFLAGS) mySplitCommandLine.cpp
myAddExeFlag.o : myAddExeFlag.cpp
	$(CXX) $(CXXFLAGS) myAddExeFlag.cpp
myGetTickCount.o : myGetTickCount.cpp
	$(CXX) $(CXXFLAGS) myGetTickCount.cpp
test_emul.o : test_emul.cpp
	$(CXX) $(CXXFLAGS) test_emul.cpp
wine_date_and_time.o : wine_date_and_time.cpp
	$(CXX) $(CXXFLAGS) wine_date_and_time.cpp
wine_GetXXXDefaultLangID.o : wine_GetXXXDefaultLangID.cpp
	$(CXX) $(CXXFLAGS) wine_GetXXXDefaultLangID.cpp
MyVector.o : ../Common/MyVector.cpp
	$(CXX) $(CXXFLAGS) ../Common/MyVector.cpp
MyString.o : ../Common/MyString.cpp
	$(CXX) $(CXXFLAGS) ../Common/MyString.cpp
MyWindows.o : ../Common/MyWindows.cpp
	$(CXX) $(CXXFLAGS) ../Common/MyWindows.cpp
