/********************************************************************************
** Form generated from reading UI file 'application.ui'
**
** Created by: Qt User Interface Compiler version 4.8.6
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef APPLICATION_H
#define APPLICATION_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QHeaderView>
#include <QtGui/QMainWindow>
#include <QtGui/QMenu>
#include <QtGui/QMenuBar>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_mainWindow
{
public:
    QAction *action_Open;
    QAction *action_Quit;
    QAction *action_Hard_Reset;
    QAction *action_Soft_Reset;
    QAction *action_Eject_Insert_Disk;
    QAction *action_Disk_1_side_A;
    QAction *action_Disk_1_side_B;
    QAction *action_Disk_2_side_A;
    QAction *action_Disk_2_side_B;
    QAction *action_Disk_3_side_A;
    QAction *action_Disk_3_side_B;
    QAction *action_Disk_4_side_A;
    QAction *action_Disk_4_side_B;
    QAction *action_Switch_sides;
    QAction *action_PAL;
    QAction *action_NTSC;
    QAction *action_Dendy;
    QAction *action_Mode_Auto;
    QAction *action_Rend0;
    QAction *action_Rend1;
    QAction *action_Rend2;
    QAction *action_FPS_Default;
    QAction *action_FPS_60;
    QAction *action_FPS_59;
    QAction *action_FPS_58;
    QAction *action_FPS_57;
    QAction *action_FPS_56;
    QAction *action_FPS_55;
    QAction *action_FPS_54;
    QAction *action_FPS_53;
    QAction *action_FPS_52;
    QAction *action_FPS_51;
    QAction *action_FPS_50;
    QAction *action_FPS_49;
    QAction *action_FPS_48;
    QAction *action_FPS_47;
    QAction *action_FPS_46;
    QAction *action_FPS_45;
    QAction *action_FPS_44;
    QAction *action_Fsk_Default;
    QAction *action_Fsk_1;
    QAction *action_Fsk_2;
    QAction *action_Fsk_3;
    QAction *action_Fsk_4;
    QAction *action_Fsk_5;
    QAction *action_Fsk_6;
    QAction *action_Fsk_7;
    QAction *action_Fsk_8;
    QAction *action_Fsk_9;
    QAction *action_1x;
    QAction *action_2x;
    QAction *action_3x;
    QAction *action_4x;
    QAction *action_PAR_11;
    QAction *action_PAR_54;
    QAction *action_PAR_87;
    QAction *action_PAR_Soft_Stretch;
    QAction *action_Oscan_Default;
    QAction *action_Oscan_On;
    QAction *action_Oscan_Off;
    QAction *action_Oscan_Def_On;
    QAction *action_Oscan_Def_Off;
    QAction *action_Oscan_Set_Borders;
    QAction *action_No_Filter;
    QAction *action_Phosphor;
    QAction *action_Phosphor2;
    QAction *action_Scanline;
    QAction *action_DBL;
    QAction *action_Dark_Room;
    QAction *action_CRT_With_Curve;
    QAction *action_CRT_Without_Curve;
    QAction *action_Scale2X;
    QAction *action_Scale3X;
    QAction *action_Scale4X;
    QAction *action_Hq2X;
    QAction *action_Hq3X;
    QAction *action_Hq4X;
    QAction *action_xBRZ_2X;
    QAction *action_xBRZ_3X;
    QAction *action_xBRZ_4X;
    QAction *action_NTSC_Composite;
    QAction *action_NTSC_SVideo;
    QAction *action_NTSC_RGB;
    QAction *action_Palette_PAL;
    QAction *action_Palette_NTSC;
    QAction *action_Sony_CXA2025AS_US;
    QAction *action_Monochrome;
    QAction *action_Green;
    QAction *action_Palette_File;
    QAction *action_Palette_Save_File;
    QAction *action_Palette_Load_File;
    QAction *actionShaders;
    QAction *action_Cube;
    QAction *action_VSync;
    QAction *action_Interpolation;
    QAction *action_Text_on_screen;
    QAction *action_Fullscreen;
    QAction *action_Stretch_in_fullscreen;
    QAction *action_Sample_rate_44100;
    QAction *action_Sample_rate_48000;
    QAction *action_Sample_rate_22050;
    QAction *action_Sample_rate_11025;
    QAction *action_Mono;
    QAction *action_Stereo;
    QAction *action_Stereo_delay_5;
    QAction *action_Stereo_delay_10;
    QAction *action_Stereo_delay_15;
    QAction *action_Stereo_delay_20;
    QAction *action_Stereo_delay_25;
    QAction *action_Stereo_delay_30;
    QAction *action_Stereo_delay_35;
    QAction *action_Stereo_delay_40;
    QAction *action_Stereo_delay_45;
    QAction *action_Stereo_delay_50;
    QAction *action_Stereo_delay_55;
    QAction *action_Stereo_delay_60;
    QAction *action_Stereo_delay_65;
    QAction *action_Stereo_delay_70;
    QAction *action_Stereo_delay_75;
    QAction *action_Stereo_delay_80;
    QAction *action_Stereo_delay_85;
    QAction *action_Stereo_delay_90;
    QAction *action_Stereo_delay_95;
    QAction *action_Stereo_delay_100;
    QAction *action_Audio_Quality_Low;
    QAction *action_Audio_Quality_High;
    QAction *action_APU_channels;
    QAction *action_Swap_Duty_Cycles;
    QAction *action_Audio_Enable;
    QAction *action_Input_Config;
    QAction *action_Pause_when_in_background;
    QAction *action_Game_Genie;
    QAction *action_Save_settings;
    QAction *action_Save_settings_on_exit;
    QAction *action_Save_state;
    QAction *action_Load_state;
    QAction *action_Increment_slot;
    QAction *action_Decrement_slot;
    QAction *action_State_Slot_0;
    QAction *action_State_Slot_1;
    QAction *action_State_Slot_2;
    QAction *action_State_Slot_3;
    QAction *action_State_Slot_4;
    QAction *action_State_Slot_5;
    QAction *action_About;
    QWidget *centralwidget;
    QMenuBar *menubar;
    QMenu *menu_File;
    QMenu *menu_Recent_Roms;
    QMenu *menu_NES;
    QMenu *menu_Disk_Side;
    QMenu *menu_Settings;
    QMenu *menu_Mode;
    QMenu *menu_Video;
    QMenu *menu_Rendering;
    QMenu *menu_FPS;
    QMenu *menu_Frame_skip;
    QMenu *menu_Scale;
    QMenu *menu_Pixel_Aspect_Ratio;
    QMenu *menu_Overscan;
    QMenu *menu_Oscan_Default_Value;
    QMenu *menu_Filter;
    QMenu *menu_Palette;
    QMenu *menu_Effect;
    QMenu *menu_Audio;
    QMenu *menu_Sample_rate;
    QMenu *menu_Channels;
    QMenu *menu_Stereo_delay;
    QMenu *menu_Audio_Quality;
    QMenu *menu_Input;
    QMenu *menu_State;
    QMenu *menu_Help;

    void setupUi(QMainWindow *mainWindow)
    {
        if (mainWindow->objectName().isEmpty())
            mainWindow->setObjectName(QString::fromUtf8("mainWindow"));
        mainWindow->setWindowModality(Qt::NonModal);
        mainWindow->resize(304, 312);
        QSizePolicy sizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(mainWindow->sizePolicy().hasHeightForWidth());
        mainWindow->setSizePolicy(sizePolicy);
        mainWindow->setMinimumSize(QSize(0, 0));
        mainWindow->setMaximumSize(QSize(16777215, 16777215));
        mainWindow->setWindowTitle(QString::fromUtf8("FHorse"));
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/icon/icons/application.png"), QSize(), QIcon::Normal, QIcon::Off);
        mainWindow->setWindowIcon(icon);
        action_Open = new QAction(mainWindow);
        action_Open->setObjectName(QString::fromUtf8("action_Open"));
        action_Open->setEnabled(true);
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/icon/icons/open.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_Open->setIcon(icon1);
        action_Quit = new QAction(mainWindow);
        action_Quit->setObjectName(QString::fromUtf8("action_Quit"));
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/icon/icons/exit.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_Quit->setIcon(icon2);
        action_Hard_Reset = new QAction(mainWindow);
        action_Hard_Reset->setObjectName(QString::fromUtf8("action_Hard_Reset"));
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/icon/icons/hard_reset.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_Hard_Reset->setIcon(icon3);
        action_Soft_Reset = new QAction(mainWindow);
        action_Soft_Reset->setObjectName(QString::fromUtf8("action_Soft_Reset"));
        QIcon icon4;
        icon4.addFile(QString::fromUtf8(":/icon/icons/soft_reset.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_Soft_Reset->setIcon(icon4);
        action_Eject_Insert_Disk = new QAction(mainWindow);
        action_Eject_Insert_Disk->setObjectName(QString::fromUtf8("action_Eject_Insert_Disk"));
        QIcon icon5;
        icon5.addFile(QString::fromUtf8(":/icon/icons/eject.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_Eject_Insert_Disk->setIcon(icon5);
        action_Disk_1_side_A = new QAction(mainWindow);
        action_Disk_1_side_A->setObjectName(QString::fromUtf8("action_Disk_1_side_A"));
        action_Disk_1_side_A->setCheckable(true);
        action_Disk_1_side_B = new QAction(mainWindow);
        action_Disk_1_side_B->setObjectName(QString::fromUtf8("action_Disk_1_side_B"));
        action_Disk_1_side_B->setCheckable(true);
        action_Disk_2_side_A = new QAction(mainWindow);
        action_Disk_2_side_A->setObjectName(QString::fromUtf8("action_Disk_2_side_A"));
        action_Disk_2_side_A->setCheckable(true);
        action_Disk_2_side_B = new QAction(mainWindow);
        action_Disk_2_side_B->setObjectName(QString::fromUtf8("action_Disk_2_side_B"));
        action_Disk_2_side_B->setCheckable(true);
        action_Disk_3_side_A = new QAction(mainWindow);
        action_Disk_3_side_A->setObjectName(QString::fromUtf8("action_Disk_3_side_A"));
        action_Disk_3_side_A->setCheckable(true);
        action_Disk_3_side_B = new QAction(mainWindow);
        action_Disk_3_side_B->setObjectName(QString::fromUtf8("action_Disk_3_side_B"));
        action_Disk_3_side_B->setCheckable(true);
        action_Disk_4_side_A = new QAction(mainWindow);
        action_Disk_4_side_A->setObjectName(QString::fromUtf8("action_Disk_4_side_A"));
        action_Disk_4_side_A->setCheckable(true);
        action_Disk_4_side_B = new QAction(mainWindow);
        action_Disk_4_side_B->setObjectName(QString::fromUtf8("action_Disk_4_side_B"));
        action_Disk_4_side_B->setCheckable(true);
        action_Switch_sides = new QAction(mainWindow);
        action_Switch_sides->setObjectName(QString::fromUtf8("action_Switch_sides"));
        QIcon icon6;
        icon6.addFile(QString::fromUtf8(":/icon/icons/switch_sides.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_Switch_sides->setIcon(icon6);
        action_PAL = new QAction(mainWindow);
        action_PAL->setObjectName(QString::fromUtf8("action_PAL"));
        action_PAL->setCheckable(true);
        action_NTSC = new QAction(mainWindow);
        action_NTSC->setObjectName(QString::fromUtf8("action_NTSC"));
        action_NTSC->setCheckable(true);
        action_Dendy = new QAction(mainWindow);
        action_Dendy->setObjectName(QString::fromUtf8("action_Dendy"));
        action_Dendy->setCheckable(true);
        action_Mode_Auto = new QAction(mainWindow);
        action_Mode_Auto->setObjectName(QString::fromUtf8("action_Mode_Auto"));
        action_Mode_Auto->setCheckable(true);
        action_Rend0 = new QAction(mainWindow);
        action_Rend0->setObjectName(QString::fromUtf8("action_Rend0"));
        action_Rend0->setCheckable(true);
        action_Rend0->setEnabled(false);
        action_Rend0->setText(QString::fromUtf8("Rend0"));
        action_Rend0->setVisible(false);
        action_Rend1 = new QAction(mainWindow);
        action_Rend1->setObjectName(QString::fromUtf8("action_Rend1"));
        action_Rend1->setCheckable(true);
        action_Rend1->setEnabled(false);
        action_Rend1->setText(QString::fromUtf8("Rend1"));
        action_Rend1->setVisible(false);
        action_Rend2 = new QAction(mainWindow);
        action_Rend2->setObjectName(QString::fromUtf8("action_Rend2"));
        action_Rend2->setCheckable(true);
        action_Rend2->setEnabled(false);
        action_Rend2->setText(QString::fromUtf8("Rend2"));
        action_Rend2->setVisible(false);
        action_FPS_Default = new QAction(mainWindow);
        action_FPS_Default->setObjectName(QString::fromUtf8("action_FPS_Default"));
        action_FPS_Default->setCheckable(true);
        action_FPS_60 = new QAction(mainWindow);
        action_FPS_60->setObjectName(QString::fromUtf8("action_FPS_60"));
        action_FPS_60->setCheckable(true);
        action_FPS_59 = new QAction(mainWindow);
        action_FPS_59->setObjectName(QString::fromUtf8("action_FPS_59"));
        action_FPS_59->setCheckable(true);
        action_FPS_58 = new QAction(mainWindow);
        action_FPS_58->setObjectName(QString::fromUtf8("action_FPS_58"));
        action_FPS_58->setCheckable(true);
        action_FPS_57 = new QAction(mainWindow);
        action_FPS_57->setObjectName(QString::fromUtf8("action_FPS_57"));
        action_FPS_57->setCheckable(true);
        action_FPS_56 = new QAction(mainWindow);
        action_FPS_56->setObjectName(QString::fromUtf8("action_FPS_56"));
        action_FPS_56->setCheckable(true);
        action_FPS_55 = new QAction(mainWindow);
        action_FPS_55->setObjectName(QString::fromUtf8("action_FPS_55"));
        action_FPS_55->setCheckable(true);
        action_FPS_54 = new QAction(mainWindow);
        action_FPS_54->setObjectName(QString::fromUtf8("action_FPS_54"));
        action_FPS_54->setCheckable(true);
        action_FPS_53 = new QAction(mainWindow);
        action_FPS_53->setObjectName(QString::fromUtf8("action_FPS_53"));
        action_FPS_53->setCheckable(true);
        action_FPS_52 = new QAction(mainWindow);
        action_FPS_52->setObjectName(QString::fromUtf8("action_FPS_52"));
        action_FPS_52->setCheckable(true);
        action_FPS_51 = new QAction(mainWindow);
        action_FPS_51->setObjectName(QString::fromUtf8("action_FPS_51"));
        action_FPS_51->setCheckable(true);
        action_FPS_50 = new QAction(mainWindow);
        action_FPS_50->setObjectName(QString::fromUtf8("action_FPS_50"));
        action_FPS_50->setCheckable(true);
        action_FPS_49 = new QAction(mainWindow);
        action_FPS_49->setObjectName(QString::fromUtf8("action_FPS_49"));
        action_FPS_49->setCheckable(true);
        action_FPS_48 = new QAction(mainWindow);
        action_FPS_48->setObjectName(QString::fromUtf8("action_FPS_48"));
        action_FPS_48->setCheckable(true);
        action_FPS_47 = new QAction(mainWindow);
        action_FPS_47->setObjectName(QString::fromUtf8("action_FPS_47"));
        action_FPS_47->setCheckable(true);
        action_FPS_46 = new QAction(mainWindow);
        action_FPS_46->setObjectName(QString::fromUtf8("action_FPS_46"));
        action_FPS_46->setCheckable(true);
        action_FPS_45 = new QAction(mainWindow);
        action_FPS_45->setObjectName(QString::fromUtf8("action_FPS_45"));
        action_FPS_45->setCheckable(true);
        action_FPS_44 = new QAction(mainWindow);
        action_FPS_44->setObjectName(QString::fromUtf8("action_FPS_44"));
        action_FPS_44->setCheckable(true);
        action_Fsk_Default = new QAction(mainWindow);
        action_Fsk_Default->setObjectName(QString::fromUtf8("action_Fsk_Default"));
        action_Fsk_Default->setCheckable(true);
        action_Fsk_1 = new QAction(mainWindow);
        action_Fsk_1->setObjectName(QString::fromUtf8("action_Fsk_1"));
        action_Fsk_1->setCheckable(true);
        action_Fsk_2 = new QAction(mainWindow);
        action_Fsk_2->setObjectName(QString::fromUtf8("action_Fsk_2"));
        action_Fsk_2->setCheckable(true);
        action_Fsk_3 = new QAction(mainWindow);
        action_Fsk_3->setObjectName(QString::fromUtf8("action_Fsk_3"));
        action_Fsk_3->setCheckable(true);
        action_Fsk_4 = new QAction(mainWindow);
        action_Fsk_4->setObjectName(QString::fromUtf8("action_Fsk_4"));
        action_Fsk_4->setCheckable(true);
        action_Fsk_5 = new QAction(mainWindow);
        action_Fsk_5->setObjectName(QString::fromUtf8("action_Fsk_5"));
        action_Fsk_5->setCheckable(true);
        action_Fsk_6 = new QAction(mainWindow);
        action_Fsk_6->setObjectName(QString::fromUtf8("action_Fsk_6"));
        action_Fsk_6->setCheckable(true);
        action_Fsk_7 = new QAction(mainWindow);
        action_Fsk_7->setObjectName(QString::fromUtf8("action_Fsk_7"));
        action_Fsk_7->setCheckable(true);
        action_Fsk_8 = new QAction(mainWindow);
        action_Fsk_8->setObjectName(QString::fromUtf8("action_Fsk_8"));
        action_Fsk_8->setCheckable(true);
        action_Fsk_9 = new QAction(mainWindow);
        action_Fsk_9->setObjectName(QString::fromUtf8("action_Fsk_9"));
        action_Fsk_9->setCheckable(true);
        action_1x = new QAction(mainWindow);
        action_1x->setObjectName(QString::fromUtf8("action_1x"));
        action_1x->setCheckable(true);
        action_1x->setText(QString::fromUtf8("&1x"));
        action_2x = new QAction(mainWindow);
        action_2x->setObjectName(QString::fromUtf8("action_2x"));
        action_2x->setCheckable(true);
        action_2x->setText(QString::fromUtf8("&2x"));
        action_3x = new QAction(mainWindow);
        action_3x->setObjectName(QString::fromUtf8("action_3x"));
        action_3x->setCheckable(true);
        action_3x->setText(QString::fromUtf8("&3x"));
        action_4x = new QAction(mainWindow);
        action_4x->setObjectName(QString::fromUtf8("action_4x"));
        action_4x->setCheckable(true);
        action_4x->setText(QString::fromUtf8("&4x"));
        action_PAR_11 = new QAction(mainWindow);
        action_PAR_11->setObjectName(QString::fromUtf8("action_PAR_11"));
        action_PAR_11->setCheckable(true);
        action_PAR_11->setText(QString::fromUtf8("&1:1"));
        action_PAR_54 = new QAction(mainWindow);
        action_PAR_54->setObjectName(QString::fromUtf8("action_PAR_54"));
        action_PAR_54->setCheckable(true);
        action_PAR_54->setText(QString::fromUtf8("&5:4"));
        action_PAR_87 = new QAction(mainWindow);
        action_PAR_87->setObjectName(QString::fromUtf8("action_PAR_87"));
        action_PAR_87->setCheckable(true);
        action_PAR_87->setText(QString::fromUtf8("&8:7 (NTSC TV)"));
        action_PAR_Soft_Stretch = new QAction(mainWindow);
        action_PAR_Soft_Stretch->setObjectName(QString::fromUtf8("action_PAR_Soft_Stretch"));
        action_PAR_Soft_Stretch->setCheckable(true);
        action_PAR_Soft_Stretch->setText(QString::fromUtf8("Soft stretch"));
        action_Oscan_Default = new QAction(mainWindow);
        action_Oscan_Default->setObjectName(QString::fromUtf8("action_Oscan_Default"));
        action_Oscan_Default->setCheckable(true);
        action_Oscan_On = new QAction(mainWindow);
        action_Oscan_On->setObjectName(QString::fromUtf8("action_Oscan_On"));
        action_Oscan_On->setCheckable(true);
        action_Oscan_Off = new QAction(mainWindow);
        action_Oscan_Off->setObjectName(QString::fromUtf8("action_Oscan_Off"));
        action_Oscan_Off->setCheckable(true);
        action_Oscan_Def_On = new QAction(mainWindow);
        action_Oscan_Def_On->setObjectName(QString::fromUtf8("action_Oscan_Def_On"));
        action_Oscan_Def_On->setCheckable(true);
        action_Oscan_Def_Off = new QAction(mainWindow);
        action_Oscan_Def_Off->setObjectName(QString::fromUtf8("action_Oscan_Def_Off"));
        action_Oscan_Def_Off->setCheckable(true);
        action_Oscan_Set_Borders = new QAction(mainWindow);
        action_Oscan_Set_Borders->setObjectName(QString::fromUtf8("action_Oscan_Set_Borders"));
        QIcon icon7;
        icon7.addFile(QString::fromUtf8(":/icon/icons/overscan_set_borders.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_Oscan_Set_Borders->setIcon(icon7);
        action_No_Filter = new QAction(mainWindow);
        action_No_Filter->setObjectName(QString::fromUtf8("action_No_Filter"));
        action_No_Filter->setCheckable(true);
        action_Phosphor = new QAction(mainWindow);
        action_Phosphor->setObjectName(QString::fromUtf8("action_Phosphor"));
        action_Phosphor->setCheckable(true);
        action_Phosphor2 = new QAction(mainWindow);
        action_Phosphor2->setObjectName(QString::fromUtf8("action_Phosphor2"));
        action_Phosphor2->setCheckable(true);
        action_Scanline = new QAction(mainWindow);
        action_Scanline->setObjectName(QString::fromUtf8("action_Scanline"));
        action_Scanline->setCheckable(true);
        action_DBL = new QAction(mainWindow);
        action_DBL->setObjectName(QString::fromUtf8("action_DBL"));
        action_DBL->setCheckable(true);
        action_Dark_Room = new QAction(mainWindow);
        action_Dark_Room->setObjectName(QString::fromUtf8("action_Dark_Room"));
        action_Dark_Room->setCheckable(true);
        action_CRT_With_Curve = new QAction(mainWindow);
        action_CRT_With_Curve->setObjectName(QString::fromUtf8("action_CRT_With_Curve"));
        action_CRT_With_Curve->setCheckable(true);
        action_CRT_Without_Curve = new QAction(mainWindow);
        action_CRT_Without_Curve->setObjectName(QString::fromUtf8("action_CRT_Without_Curve"));
        action_CRT_Without_Curve->setCheckable(true);
        action_Scale2X = new QAction(mainWindow);
        action_Scale2X->setObjectName(QString::fromUtf8("action_Scale2X"));
        action_Scale2X->setCheckable(true);
        action_Scale3X = new QAction(mainWindow);
        action_Scale3X->setObjectName(QString::fromUtf8("action_Scale3X"));
        action_Scale3X->setCheckable(true);
        action_Scale4X = new QAction(mainWindow);
        action_Scale4X->setObjectName(QString::fromUtf8("action_Scale4X"));
        action_Scale4X->setCheckable(true);
        action_Hq2X = new QAction(mainWindow);
        action_Hq2X->setObjectName(QString::fromUtf8("action_Hq2X"));
        action_Hq2X->setCheckable(true);
        action_Hq3X = new QAction(mainWindow);
        action_Hq3X->setObjectName(QString::fromUtf8("action_Hq3X"));
        action_Hq3X->setCheckable(true);
        action_Hq4X = new QAction(mainWindow);
        action_Hq4X->setObjectName(QString::fromUtf8("action_Hq4X"));
        action_Hq4X->setCheckable(true);
        action_xBRZ_2X = new QAction(mainWindow);
        action_xBRZ_2X->setObjectName(QString::fromUtf8("action_xBRZ_2X"));
        action_xBRZ_2X->setCheckable(true);
        action_xBRZ_3X = new QAction(mainWindow);
        action_xBRZ_3X->setObjectName(QString::fromUtf8("action_xBRZ_3X"));
        action_xBRZ_3X->setCheckable(true);
        action_xBRZ_4X = new QAction(mainWindow);
        action_xBRZ_4X->setObjectName(QString::fromUtf8("action_xBRZ_4X"));
        action_xBRZ_4X->setCheckable(true);
        action_NTSC_Composite = new QAction(mainWindow);
        action_NTSC_Composite->setObjectName(QString::fromUtf8("action_NTSC_Composite"));
        action_NTSC_Composite->setCheckable(true);
        action_NTSC_SVideo = new QAction(mainWindow);
        action_NTSC_SVideo->setObjectName(QString::fromUtf8("action_NTSC_SVideo"));
        action_NTSC_SVideo->setCheckable(true);
        action_NTSC_RGB = new QAction(mainWindow);
        action_NTSC_RGB->setObjectName(QString::fromUtf8("action_NTSC_RGB"));
        action_NTSC_RGB->setCheckable(true);
        action_Palette_PAL = new QAction(mainWindow);
        action_Palette_PAL->setObjectName(QString::fromUtf8("action_Palette_PAL"));
        action_Palette_PAL->setCheckable(true);
        action_Palette_NTSC = new QAction(mainWindow);
        action_Palette_NTSC->setObjectName(QString::fromUtf8("action_Palette_NTSC"));
        action_Palette_NTSC->setCheckable(true);
        action_Sony_CXA2025AS_US = new QAction(mainWindow);
        action_Sony_CXA2025AS_US->setObjectName(QString::fromUtf8("action_Sony_CXA2025AS_US"));
        action_Sony_CXA2025AS_US->setCheckable(true);
        action_Monochrome = new QAction(mainWindow);
        action_Monochrome->setObjectName(QString::fromUtf8("action_Monochrome"));
        action_Monochrome->setCheckable(true);
        action_Green = new QAction(mainWindow);
        action_Green->setObjectName(QString::fromUtf8("action_Green"));
        action_Green->setCheckable(true);
        action_Palette_File = new QAction(mainWindow);
        action_Palette_File->setObjectName(QString::fromUtf8("action_Palette_File"));
        action_Palette_File->setCheckable(true);
        action_Palette_File->setText(QString::fromUtf8("[Select a file]"));
        action_Palette_Save_File = new QAction(mainWindow);
        action_Palette_Save_File->setObjectName(QString::fromUtf8("action_Palette_Save_File"));
        QIcon icon8;
        icon8.addFile(QString::fromUtf8(":/icon/icons/save.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_Palette_Save_File->setIcon(icon8);
        action_Palette_Load_File = new QAction(mainWindow);
        action_Palette_Load_File->setObjectName(QString::fromUtf8("action_Palette_Load_File"));
        QIcon icon9;
        icon9.addFile(QString::fromUtf8(":/icon/icons/load.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_Palette_Load_File->setIcon(icon9);
        actionShaders = new QAction(mainWindow);
        actionShaders->setObjectName(QString::fromUtf8("actionShaders"));
        actionShaders->setEnabled(false);
        action_Cube = new QAction(mainWindow);
        action_Cube->setObjectName(QString::fromUtf8("action_Cube"));
        action_Cube->setCheckable(true);
        action_VSync = new QAction(mainWindow);
        action_VSync->setObjectName(QString::fromUtf8("action_VSync"));
        action_VSync->setCheckable(true);
        action_Interpolation = new QAction(mainWindow);
        action_Interpolation->setObjectName(QString::fromUtf8("action_Interpolation"));
        action_Interpolation->setCheckable(true);
        action_Text_on_screen = new QAction(mainWindow);
        action_Text_on_screen->setObjectName(QString::fromUtf8("action_Text_on_screen"));
        action_Text_on_screen->setCheckable(true);
        action_Fullscreen = new QAction(mainWindow);
        action_Fullscreen->setObjectName(QString::fromUtf8("action_Fullscreen"));
        QIcon icon10;
        icon10.addFile(QString::fromUtf8(":/icon/icons/fullscreen.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_Fullscreen->setIcon(icon10);
        action_Stretch_in_fullscreen = new QAction(mainWindow);
        action_Stretch_in_fullscreen->setObjectName(QString::fromUtf8("action_Stretch_in_fullscreen"));
        action_Stretch_in_fullscreen->setCheckable(true);
        action_Sample_rate_44100 = new QAction(mainWindow);
        action_Sample_rate_44100->setObjectName(QString::fromUtf8("action_Sample_rate_44100"));
        action_Sample_rate_44100->setCheckable(true);
        action_Sample_rate_48000 = new QAction(mainWindow);
        action_Sample_rate_48000->setObjectName(QString::fromUtf8("action_Sample_rate_48000"));
        action_Sample_rate_48000->setCheckable(true);
        action_Sample_rate_22050 = new QAction(mainWindow);
        action_Sample_rate_22050->setObjectName(QString::fromUtf8("action_Sample_rate_22050"));
        action_Sample_rate_22050->setCheckable(true);
        action_Sample_rate_11025 = new QAction(mainWindow);
        action_Sample_rate_11025->setObjectName(QString::fromUtf8("action_Sample_rate_11025"));
        action_Sample_rate_11025->setCheckable(true);
        action_Mono = new QAction(mainWindow);
        action_Mono->setObjectName(QString::fromUtf8("action_Mono"));
        action_Mono->setCheckable(true);
        action_Stereo = new QAction(mainWindow);
        action_Stereo->setObjectName(QString::fromUtf8("action_Stereo"));
        action_Stereo->setCheckable(true);
        action_Stereo_delay_5 = new QAction(mainWindow);
        action_Stereo_delay_5->setObjectName(QString::fromUtf8("action_Stereo_delay_5"));
        action_Stereo_delay_5->setCheckable(true);
        action_Stereo_delay_10 = new QAction(mainWindow);
        action_Stereo_delay_10->setObjectName(QString::fromUtf8("action_Stereo_delay_10"));
        action_Stereo_delay_10->setCheckable(true);
        action_Stereo_delay_15 = new QAction(mainWindow);
        action_Stereo_delay_15->setObjectName(QString::fromUtf8("action_Stereo_delay_15"));
        action_Stereo_delay_15->setCheckable(true);
        action_Stereo_delay_20 = new QAction(mainWindow);
        action_Stereo_delay_20->setObjectName(QString::fromUtf8("action_Stereo_delay_20"));
        action_Stereo_delay_20->setCheckable(true);
        action_Stereo_delay_25 = new QAction(mainWindow);
        action_Stereo_delay_25->setObjectName(QString::fromUtf8("action_Stereo_delay_25"));
        action_Stereo_delay_25->setCheckable(true);
        action_Stereo_delay_30 = new QAction(mainWindow);
        action_Stereo_delay_30->setObjectName(QString::fromUtf8("action_Stereo_delay_30"));
        action_Stereo_delay_30->setCheckable(true);
        action_Stereo_delay_35 = new QAction(mainWindow);
        action_Stereo_delay_35->setObjectName(QString::fromUtf8("action_Stereo_delay_35"));
        action_Stereo_delay_35->setCheckable(true);
        action_Stereo_delay_40 = new QAction(mainWindow);
        action_Stereo_delay_40->setObjectName(QString::fromUtf8("action_Stereo_delay_40"));
        action_Stereo_delay_40->setCheckable(true);
        action_Stereo_delay_45 = new QAction(mainWindow);
        action_Stereo_delay_45->setObjectName(QString::fromUtf8("action_Stereo_delay_45"));
        action_Stereo_delay_45->setCheckable(true);
        action_Stereo_delay_50 = new QAction(mainWindow);
        action_Stereo_delay_50->setObjectName(QString::fromUtf8("action_Stereo_delay_50"));
        action_Stereo_delay_50->setCheckable(true);
        action_Stereo_delay_55 = new QAction(mainWindow);
        action_Stereo_delay_55->setObjectName(QString::fromUtf8("action_Stereo_delay_55"));
        action_Stereo_delay_55->setCheckable(true);
        action_Stereo_delay_60 = new QAction(mainWindow);
        action_Stereo_delay_60->setObjectName(QString::fromUtf8("action_Stereo_delay_60"));
        action_Stereo_delay_60->setCheckable(true);
        action_Stereo_delay_65 = new QAction(mainWindow);
        action_Stereo_delay_65->setObjectName(QString::fromUtf8("action_Stereo_delay_65"));
        action_Stereo_delay_65->setCheckable(true);
        action_Stereo_delay_70 = new QAction(mainWindow);
        action_Stereo_delay_70->setObjectName(QString::fromUtf8("action_Stereo_delay_70"));
        action_Stereo_delay_70->setCheckable(true);
        action_Stereo_delay_75 = new QAction(mainWindow);
        action_Stereo_delay_75->setObjectName(QString::fromUtf8("action_Stereo_delay_75"));
        action_Stereo_delay_75->setCheckable(true);
        action_Stereo_delay_80 = new QAction(mainWindow);
        action_Stereo_delay_80->setObjectName(QString::fromUtf8("action_Stereo_delay_80"));
        action_Stereo_delay_80->setCheckable(true);
        action_Stereo_delay_85 = new QAction(mainWindow);
        action_Stereo_delay_85->setObjectName(QString::fromUtf8("action_Stereo_delay_85"));
        action_Stereo_delay_85->setCheckable(true);
        action_Stereo_delay_90 = new QAction(mainWindow);
        action_Stereo_delay_90->setObjectName(QString::fromUtf8("action_Stereo_delay_90"));
        action_Stereo_delay_90->setCheckable(true);
        action_Stereo_delay_95 = new QAction(mainWindow);
        action_Stereo_delay_95->setObjectName(QString::fromUtf8("action_Stereo_delay_95"));
        action_Stereo_delay_95->setCheckable(true);
        action_Stereo_delay_100 = new QAction(mainWindow);
        action_Stereo_delay_100->setObjectName(QString::fromUtf8("action_Stereo_delay_100"));
        action_Stereo_delay_100->setCheckable(true);
        action_Audio_Quality_Low = new QAction(mainWindow);
        action_Audio_Quality_Low->setObjectName(QString::fromUtf8("action_Audio_Quality_Low"));
        action_Audio_Quality_Low->setCheckable(true);
        action_Audio_Quality_High = new QAction(mainWindow);
        action_Audio_Quality_High->setObjectName(QString::fromUtf8("action_Audio_Quality_High"));
        action_Audio_Quality_High->setCheckable(true);
        action_APU_channels = new QAction(mainWindow);
        action_APU_channels->setObjectName(QString::fromUtf8("action_APU_channels"));
        QIcon icon11;
        icon11.addFile(QString::fromUtf8(":/icon/icons/apu_channels.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_APU_channels->setIcon(icon11);
        action_Swap_Duty_Cycles = new QAction(mainWindow);
        action_Swap_Duty_Cycles->setObjectName(QString::fromUtf8("action_Swap_Duty_Cycles"));
        action_Swap_Duty_Cycles->setCheckable(true);
        action_Audio_Enable = new QAction(mainWindow);
        action_Audio_Enable->setObjectName(QString::fromUtf8("action_Audio_Enable"));
        action_Audio_Enable->setCheckable(true);
        action_Input_Config = new QAction(mainWindow);
        action_Input_Config->setObjectName(QString::fromUtf8("action_Input_Config"));
        QIcon icon12;
        icon12.addFile(QString::fromUtf8(":/icon/icons/input_config.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_Input_Config->setIcon(icon12);
        action_Pause_when_in_background = new QAction(mainWindow);
        action_Pause_when_in_background->setObjectName(QString::fromUtf8("action_Pause_when_in_background"));
        action_Pause_when_in_background->setCheckable(true);
        action_Game_Genie = new QAction(mainWindow);
        action_Game_Genie->setObjectName(QString::fromUtf8("action_Game_Genie"));
        action_Game_Genie->setCheckable(true);
        action_Save_settings = new QAction(mainWindow);
        action_Save_settings->setObjectName(QString::fromUtf8("action_Save_settings"));
        QIcon icon13;
        icon13.addFile(QString::fromUtf8(":/icon/icons/save_settings.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_Save_settings->setIcon(icon13);
        action_Save_settings_on_exit = new QAction(mainWindow);
        action_Save_settings_on_exit->setObjectName(QString::fromUtf8("action_Save_settings_on_exit"));
        action_Save_settings_on_exit->setCheckable(true);
        action_Save_state = new QAction(mainWindow);
        action_Save_state->setObjectName(QString::fromUtf8("action_Save_state"));
        action_Save_state->setIcon(icon8);
        action_Load_state = new QAction(mainWindow);
        action_Load_state->setObjectName(QString::fromUtf8("action_Load_state"));
        action_Load_state->setIcon(icon9);
        action_Increment_slot = new QAction(mainWindow);
        action_Increment_slot->setObjectName(QString::fromUtf8("action_Increment_slot"));
        QIcon icon14;
        icon14.addFile(QString::fromUtf8(":/icon/icons/state_inc.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_Increment_slot->setIcon(icon14);
        action_Decrement_slot = new QAction(mainWindow);
        action_Decrement_slot->setObjectName(QString::fromUtf8("action_Decrement_slot"));
        QIcon icon15;
        icon15.addFile(QString::fromUtf8(":/icon/icons/state_dec.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_Decrement_slot->setIcon(icon15);
        action_State_Slot_0 = new QAction(mainWindow);
        action_State_Slot_0->setObjectName(QString::fromUtf8("action_State_Slot_0"));
        action_State_Slot_0->setCheckable(true);
        action_State_Slot_1 = new QAction(mainWindow);
        action_State_Slot_1->setObjectName(QString::fromUtf8("action_State_Slot_1"));
        action_State_Slot_1->setCheckable(true);
        action_State_Slot_2 = new QAction(mainWindow);
        action_State_Slot_2->setObjectName(QString::fromUtf8("action_State_Slot_2"));
        action_State_Slot_2->setCheckable(true);
        action_State_Slot_3 = new QAction(mainWindow);
        action_State_Slot_3->setObjectName(QString::fromUtf8("action_State_Slot_3"));
        action_State_Slot_3->setCheckable(true);
        action_State_Slot_4 = new QAction(mainWindow);
        action_State_Slot_4->setObjectName(QString::fromUtf8("action_State_Slot_4"));
        action_State_Slot_4->setCheckable(true);
        action_State_Slot_5 = new QAction(mainWindow);
        action_State_Slot_5->setObjectName(QString::fromUtf8("action_State_Slot_5"));
        action_State_Slot_5->setCheckable(true);
        action_About = new QAction(mainWindow);
        action_About->setObjectName(QString::fromUtf8("action_About"));
        QIcon icon16;
        icon16.addFile(QString::fromUtf8(":/icon/icons/about.png"), QSize(), QIcon::Normal, QIcon::Off);
        action_About->setIcon(icon16);
        centralwidget = new QWidget(mainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        mainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(mainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 304, 26));
        menu_File = new QMenu(menubar);
        menu_File->setObjectName(QString::fromUtf8("menu_File"));
        menu_File->setTearOffEnabled(false);
        menu_Recent_Roms = new QMenu(menu_File);
        menu_Recent_Roms->setObjectName(QString::fromUtf8("menu_Recent_Roms"));
        QIcon icon17;
        icon17.addFile(QString::fromUtf8(":/icon/icons/recent_roms.png"), QSize(), QIcon::Normal, QIcon::Off);
        menu_Recent_Roms->setIcon(icon17);
        menu_NES = new QMenu(menubar);
        menu_NES->setObjectName(QString::fromUtf8("menu_NES"));
        menu_Disk_Side = new QMenu(menu_NES);
        menu_Disk_Side->setObjectName(QString::fromUtf8("menu_Disk_Side"));
        QIcon icon18;
        icon18.addFile(QString::fromUtf8(":/icon/icons/disk_side.png"), QSize(), QIcon::Normal, QIcon::Off);
        menu_Disk_Side->setIcon(icon18);
        menu_Settings = new QMenu(menubar);
        menu_Settings->setObjectName(QString::fromUtf8("menu_Settings"));
        menu_Mode = new QMenu(menu_Settings);
        menu_Mode->setObjectName(QString::fromUtf8("menu_Mode"));
        QIcon icon19;
        icon19.addFile(QString::fromUtf8(":/icon/icons/mode.png"), QSize(), QIcon::Normal, QIcon::Off);
        menu_Mode->setIcon(icon19);
        menu_Video = new QMenu(menu_Settings);
        menu_Video->setObjectName(QString::fromUtf8("menu_Video"));
        QIcon icon20;
        icon20.addFile(QString::fromUtf8(":/icon/icons/video.png"), QSize(), QIcon::Normal, QIcon::Off);
        menu_Video->setIcon(icon20);
        menu_Rendering = new QMenu(menu_Video);
        menu_Rendering->setObjectName(QString::fromUtf8("menu_Rendering"));
        QIcon icon21;
        icon21.addFile(QString::fromUtf8(":/icon/icons/rendering.png"), QSize(), QIcon::Normal, QIcon::Off);
        menu_Rendering->setIcon(icon21);
        menu_FPS = new QMenu(menu_Video);
        menu_FPS->setObjectName(QString::fromUtf8("menu_FPS"));
        QIcon icon22;
        icon22.addFile(QString::fromUtf8(":/icon/icons/fps.png"), QSize(), QIcon::Normal, QIcon::Off);
        menu_FPS->setIcon(icon22);
        menu_Frame_skip = new QMenu(menu_Video);
        menu_Frame_skip->setObjectName(QString::fromUtf8("menu_Frame_skip"));
        QIcon icon23;
        icon23.addFile(QString::fromUtf8(":/icon/icons/frameskip.png"), QSize(), QIcon::Normal, QIcon::Off);
        menu_Frame_skip->setIcon(icon23);
        menu_Scale = new QMenu(menu_Video);
        menu_Scale->setObjectName(QString::fromUtf8("menu_Scale"));
        QIcon icon24;
        icon24.addFile(QString::fromUtf8(":/icon/icons/scale.png"), QSize(), QIcon::Normal, QIcon::Off);
        menu_Scale->setIcon(icon24);
        menu_Pixel_Aspect_Ratio = new QMenu(menu_Video);
        menu_Pixel_Aspect_Ratio->setObjectName(QString::fromUtf8("menu_Pixel_Aspect_Ratio"));
        QIcon icon25;
        icon25.addFile(QString::fromUtf8(":/icon/icons/pixel_aspect_ratio.png"), QSize(), QIcon::Normal, QIcon::Off);
        menu_Pixel_Aspect_Ratio->setIcon(icon25);
        menu_Overscan = new QMenu(menu_Video);
        menu_Overscan->setObjectName(QString::fromUtf8("menu_Overscan"));
        QIcon icon26;
        icon26.addFile(QString::fromUtf8(":/icon/icons/overscan.png"), QSize(), QIcon::Normal, QIcon::Off);
        menu_Overscan->setIcon(icon26);
        menu_Oscan_Default_Value = new QMenu(menu_Overscan);
        menu_Oscan_Default_Value->setObjectName(QString::fromUtf8("menu_Oscan_Default_Value"));
        QIcon icon27;
        icon27.addFile(QString::fromUtf8(":/icon/icons/overscan_default.png"), QSize(), QIcon::Normal, QIcon::Off);
        menu_Oscan_Default_Value->setIcon(icon27);
        menu_Filter = new QMenu(menu_Video);
        menu_Filter->setObjectName(QString::fromUtf8("menu_Filter"));
        QIcon icon28;
        icon28.addFile(QString::fromUtf8(":/icon/icons/filter.png"), QSize(), QIcon::Normal, QIcon::Off);
        menu_Filter->setIcon(icon28);
        menu_Palette = new QMenu(menu_Video);
        menu_Palette->setObjectName(QString::fromUtf8("menu_Palette"));
        QIcon icon29;
        icon29.addFile(QString::fromUtf8(":/icon/icons/palette.png"), QSize(), QIcon::Normal, QIcon::Off);
        menu_Palette->setIcon(icon29);
        menu_Effect = new QMenu(menu_Video);
        menu_Effect->setObjectName(QString::fromUtf8("menu_Effect"));
        QIcon icon30;
        icon30.addFile(QString::fromUtf8(":/icon/icons/effect.png"), QSize(), QIcon::Normal, QIcon::Off);
        menu_Effect->setIcon(icon30);
        menu_Audio = new QMenu(menu_Settings);
        menu_Audio->setObjectName(QString::fromUtf8("menu_Audio"));
        QIcon icon31;
        icon31.addFile(QString::fromUtf8(":/icon/icons/audio.png"), QSize(), QIcon::Normal, QIcon::Off);
        menu_Audio->setIcon(icon31);
        menu_Sample_rate = new QMenu(menu_Audio);
        menu_Sample_rate->setObjectName(QString::fromUtf8("menu_Sample_rate"));
        QIcon icon32;
        icon32.addFile(QString::fromUtf8(":/icon/icons/samplerate.png"), QSize(), QIcon::Normal, QIcon::Off);
        menu_Sample_rate->setIcon(icon32);
        menu_Channels = new QMenu(menu_Audio);
        menu_Channels->setObjectName(QString::fromUtf8("menu_Channels"));
        QIcon icon33;
        icon33.addFile(QString::fromUtf8(":/icon/icons/channels.png"), QSize(), QIcon::Normal, QIcon::Off);
        menu_Channels->setIcon(icon33);
        menu_Stereo_delay = new QMenu(menu_Channels);
        menu_Stereo_delay->setObjectName(QString::fromUtf8("menu_Stereo_delay"));
        QIcon icon34;
        icon34.addFile(QString::fromUtf8(":/icon/icons/stereo_delay.png"), QSize(), QIcon::Normal, QIcon::Off);
        menu_Stereo_delay->setIcon(icon34);
        menu_Audio_Quality = new QMenu(menu_Audio);
        menu_Audio_Quality->setObjectName(QString::fromUtf8("menu_Audio_Quality"));
        QIcon icon35;
        icon35.addFile(QString::fromUtf8(":/icon/icons/quality.png"), QSize(), QIcon::Normal, QIcon::Off);
        menu_Audio_Quality->setIcon(icon35);
        menu_Input = new QMenu(menu_Settings);
        menu_Input->setObjectName(QString::fromUtf8("menu_Input"));
        QIcon icon36;
        icon36.addFile(QString::fromUtf8(":/icon/icons/input.png"), QSize(), QIcon::Normal, QIcon::Off);
        menu_Input->setIcon(icon36);
        menu_State = new QMenu(menubar);
        menu_State->setObjectName(QString::fromUtf8("menu_State"));
        menu_Help = new QMenu(menubar);
        menu_Help->setObjectName(QString::fromUtf8("menu_Help"));
        mainWindow->setMenuBar(menubar);

        menubar->addAction(menu_File->menuAction());
        menubar->addAction(menu_NES->menuAction());
        menubar->addAction(menu_Settings->menuAction());
        menubar->addAction(menu_State->menuAction());
        menubar->addAction(menu_Help->menuAction());
        menu_File->addAction(action_Open);
        menu_File->addAction(menu_Recent_Roms->menuAction());
        menu_File->addSeparator();
        menu_File->addAction(action_Quit);
        menu_NES->addAction(action_Hard_Reset);
        menu_NES->addAction(action_Soft_Reset);
        menu_NES->addSeparator();
        menu_NES->addAction(menu_Disk_Side->menuAction());
        menu_NES->addAction(action_Eject_Insert_Disk);
        menu_Disk_Side->addAction(action_Disk_1_side_A);
        menu_Disk_Side->addAction(action_Disk_1_side_B);
        menu_Disk_Side->addAction(action_Disk_2_side_A);
        menu_Disk_Side->addAction(action_Disk_2_side_B);
        menu_Disk_Side->addAction(action_Disk_3_side_A);
        menu_Disk_Side->addAction(action_Disk_3_side_B);
        menu_Disk_Side->addAction(action_Disk_4_side_A);
        menu_Disk_Side->addAction(action_Disk_4_side_B);
        menu_Disk_Side->addSeparator();
        menu_Disk_Side->addAction(action_Switch_sides);
        menu_Settings->addAction(menu_Mode->menuAction());
        menu_Settings->addSeparator();
        menu_Settings->addAction(menu_Video->menuAction());
        menu_Settings->addAction(menu_Audio->menuAction());
        menu_Settings->addAction(menu_Input->menuAction());
        menu_Settings->addSeparator();
        menu_Settings->addAction(action_Pause_when_in_background);
        menu_Settings->addAction(action_Game_Genie);
        menu_Settings->addAction(action_Save_settings_on_exit);
        menu_Settings->addSeparator();
        menu_Settings->addAction(action_Save_settings);
        menu_Mode->addAction(action_PAL);
        menu_Mode->addAction(action_NTSC);
        menu_Mode->addAction(action_Dendy);
        menu_Mode->addAction(action_Mode_Auto);
        menu_Video->addAction(menu_Rendering->menuAction());
        menu_Video->addAction(menu_FPS->menuAction());
        menu_Video->addAction(menu_Frame_skip->menuAction());
        menu_Video->addSeparator();
        menu_Video->addAction(menu_Scale->menuAction());
        menu_Video->addAction(menu_Pixel_Aspect_Ratio->menuAction());
        menu_Video->addAction(menu_Overscan->menuAction());
        menu_Video->addAction(menu_Filter->menuAction());
        menu_Video->addAction(menu_Palette->menuAction());
        menu_Video->addAction(menu_Effect->menuAction());
        menu_Video->addSeparator();
        menu_Video->addAction(action_VSync);
        menu_Video->addAction(action_Interpolation);
        menu_Video->addAction(action_Text_on_screen);
        menu_Video->addSeparator();
        menu_Video->addAction(action_Fullscreen);
        menu_Video->addAction(action_Stretch_in_fullscreen);
        menu_Rendering->addAction(action_Rend0);
        menu_Rendering->addAction(action_Rend1);
        menu_Rendering->addAction(action_Rend2);
        menu_FPS->addAction(action_FPS_Default);
        menu_FPS->addSeparator();
        menu_FPS->addAction(action_FPS_60);
        menu_FPS->addAction(action_FPS_59);
        menu_FPS->addAction(action_FPS_58);
        menu_FPS->addAction(action_FPS_57);
        menu_FPS->addAction(action_FPS_56);
        menu_FPS->addAction(action_FPS_55);
        menu_FPS->addAction(action_FPS_54);
        menu_FPS->addAction(action_FPS_53);
        menu_FPS->addAction(action_FPS_52);
        menu_FPS->addAction(action_FPS_51);
        menu_FPS->addAction(action_FPS_50);
        menu_FPS->addAction(action_FPS_49);
        menu_FPS->addAction(action_FPS_48);
        menu_FPS->addAction(action_FPS_47);
        menu_FPS->addAction(action_FPS_46);
        menu_FPS->addAction(action_FPS_45);
        menu_FPS->addAction(action_FPS_44);
        menu_Frame_skip->addAction(action_Fsk_Default);
        menu_Frame_skip->addSeparator();
        menu_Frame_skip->addAction(action_Fsk_1);
        menu_Frame_skip->addAction(action_Fsk_2);
        menu_Frame_skip->addAction(action_Fsk_3);
        menu_Frame_skip->addAction(action_Fsk_4);
        menu_Frame_skip->addAction(action_Fsk_5);
        menu_Frame_skip->addAction(action_Fsk_6);
        menu_Frame_skip->addAction(action_Fsk_7);
        menu_Frame_skip->addAction(action_Fsk_8);
        menu_Frame_skip->addAction(action_Fsk_9);
        menu_Scale->addAction(action_1x);
        menu_Scale->addAction(action_2x);
        menu_Scale->addAction(action_3x);
        menu_Scale->addAction(action_4x);
        menu_Pixel_Aspect_Ratio->addAction(action_PAR_11);
        menu_Pixel_Aspect_Ratio->addAction(action_PAR_54);
        menu_Pixel_Aspect_Ratio->addAction(action_PAR_87);
        menu_Pixel_Aspect_Ratio->addSeparator();
        menu_Pixel_Aspect_Ratio->addAction(action_PAR_Soft_Stretch);
        menu_Overscan->addAction(action_Oscan_Default);
        menu_Overscan->addSeparator();
        menu_Overscan->addAction(action_Oscan_On);
        menu_Overscan->addAction(action_Oscan_Off);
        menu_Overscan->addSeparator();
        menu_Overscan->addAction(menu_Oscan_Default_Value->menuAction());
        menu_Overscan->addSeparator();
        menu_Overscan->addAction(action_Oscan_Set_Borders);
        menu_Oscan_Default_Value->addAction(action_Oscan_Def_On);
        menu_Oscan_Default_Value->addAction(action_Oscan_Def_Off);
        menu_Filter->addAction(action_No_Filter);
        menu_Filter->addAction(action_Scale2X);
        menu_Filter->addAction(action_Scale3X);
        menu_Filter->addAction(action_Scale4X);
        menu_Filter->addAction(action_Hq2X);
        menu_Filter->addAction(action_Hq3X);
        menu_Filter->addAction(action_Hq4X);
        menu_Filter->addAction(action_xBRZ_2X);
        menu_Filter->addAction(action_xBRZ_3X);
        menu_Filter->addAction(action_xBRZ_4X);
        menu_Filter->addAction(action_NTSC_Composite);
        menu_Filter->addAction(action_NTSC_SVideo);
        menu_Filter->addAction(action_NTSC_RGB);
        menu_Filter->addAction(action_Phosphor);
        menu_Filter->addAction(action_Phosphor2);
        menu_Filter->addAction(action_Scanline);
        menu_Filter->addAction(action_DBL);
        menu_Filter->addAction(action_Dark_Room);
        menu_Filter->addAction(action_CRT_With_Curve);
        menu_Filter->addAction(action_CRT_Without_Curve);
        menu_Palette->addAction(action_Palette_PAL);
        menu_Palette->addAction(action_Palette_NTSC);
        menu_Palette->addAction(action_Sony_CXA2025AS_US);
        menu_Palette->addAction(action_Monochrome);
        menu_Palette->addAction(action_Green);
        menu_Palette->addSeparator();
        menu_Palette->addAction(action_Palette_File);
        menu_Palette->addSeparator();
        menu_Palette->addAction(action_Palette_Save_File);
        menu_Palette->addAction(action_Palette_Load_File);
        menu_Effect->addAction(action_Cube);
        menu_Audio->addAction(menu_Sample_rate->menuAction());
        menu_Audio->addAction(menu_Channels->menuAction());
        menu_Audio->addAction(menu_Audio_Quality->menuAction());
        menu_Audio->addAction(action_APU_channels);
        menu_Audio->addSeparator();
        menu_Audio->addAction(action_Swap_Duty_Cycles);
        menu_Audio->addAction(action_Audio_Enable);
        menu_Sample_rate->addAction(action_Sample_rate_48000);
        menu_Sample_rate->addAction(action_Sample_rate_44100);
        menu_Sample_rate->addAction(action_Sample_rate_22050);
        menu_Sample_rate->addAction(action_Sample_rate_11025);
        menu_Channels->addAction(action_Mono);
        menu_Channels->addAction(action_Stereo);
        menu_Channels->addSeparator();
        menu_Channels->addAction(menu_Stereo_delay->menuAction());
        menu_Stereo_delay->addAction(action_Stereo_delay_5);
        menu_Stereo_delay->addAction(action_Stereo_delay_10);
        menu_Stereo_delay->addAction(action_Stereo_delay_15);
        menu_Stereo_delay->addAction(action_Stereo_delay_20);
        menu_Stereo_delay->addAction(action_Stereo_delay_25);
        menu_Stereo_delay->addAction(action_Stereo_delay_30);
        menu_Stereo_delay->addAction(action_Stereo_delay_35);
        menu_Stereo_delay->addAction(action_Stereo_delay_40);
        menu_Stereo_delay->addAction(action_Stereo_delay_45);
        menu_Stereo_delay->addAction(action_Stereo_delay_50);
        menu_Stereo_delay->addAction(action_Stereo_delay_55);
        menu_Stereo_delay->addAction(action_Stereo_delay_60);
        menu_Stereo_delay->addAction(action_Stereo_delay_65);
        menu_Stereo_delay->addAction(action_Stereo_delay_70);
        menu_Stereo_delay->addAction(action_Stereo_delay_75);
        menu_Stereo_delay->addAction(action_Stereo_delay_80);
        menu_Stereo_delay->addAction(action_Stereo_delay_85);
        menu_Stereo_delay->addAction(action_Stereo_delay_90);
        menu_Stereo_delay->addAction(action_Stereo_delay_95);
        menu_Stereo_delay->addAction(action_Stereo_delay_100);
        menu_Audio_Quality->addAction(action_Audio_Quality_Low);
        menu_Audio_Quality->addAction(action_Audio_Quality_High);
        menu_Input->addAction(action_Input_Config);
        menu_State->addAction(action_Save_state);
        menu_State->addAction(action_Load_state);
        menu_State->addSeparator();
        menu_State->addAction(action_Increment_slot);
        menu_State->addAction(action_Decrement_slot);
        menu_State->addSeparator();
        menu_State->addAction(action_State_Slot_0);
        menu_State->addAction(action_State_Slot_1);
        menu_State->addAction(action_State_Slot_2);
        menu_State->addAction(action_State_Slot_3);
        menu_State->addAction(action_State_Slot_4);
        menu_State->addAction(action_State_Slot_5);
        menu_Help->addAction(action_About);

        retranslateUi(mainWindow);

        QMetaObject::connectSlotsByName(mainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *mainWindow)
    {
        action_Open->setText(QApplication::translate("mainWindow", "&Open", 0, QApplication::UnicodeUTF8));
        action_Quit->setText(QApplication::translate("mainWindow", "&Quit", 0, QApplication::UnicodeUTF8));
        action_Hard_Reset->setText(QApplication::translate("mainWindow", "&Hard Reset", 0, QApplication::UnicodeUTF8));
        action_Soft_Reset->setText(QApplication::translate("mainWindow", "&Soft Reset", 0, QApplication::UnicodeUTF8));
        action_Eject_Insert_Disk->setText(QApplication::translate("mainWindow", "&Eject/Insert Disk", 0, QApplication::UnicodeUTF8));
        action_Disk_1_side_A->setText(QApplication::translate("mainWindow", "Disk 1 side A", 0, QApplication::UnicodeUTF8));
        action_Disk_1_side_B->setText(QApplication::translate("mainWindow", "Disk 1 side B", 0, QApplication::UnicodeUTF8));
        action_Disk_2_side_A->setText(QApplication::translate("mainWindow", "Disk 2 side A", 0, QApplication::UnicodeUTF8));
        action_Disk_2_side_B->setText(QApplication::translate("mainWindow", "Disk 2 side B", 0, QApplication::UnicodeUTF8));
        action_Disk_3_side_A->setText(QApplication::translate("mainWindow", "Disk 3 side A", 0, QApplication::UnicodeUTF8));
        action_Disk_3_side_B->setText(QApplication::translate("mainWindow", "Disk 3 side B", 0, QApplication::UnicodeUTF8));
        action_Disk_4_side_A->setText(QApplication::translate("mainWindow", "Disk 4 side A", 0, QApplication::UnicodeUTF8));
        action_Disk_4_side_B->setText(QApplication::translate("mainWindow", "Disk 4 side B", 0, QApplication::UnicodeUTF8));
        action_Switch_sides->setText(QApplication::translate("mainWindow", "&Switch sides", 0, QApplication::UnicodeUTF8));
        action_PAL->setText(QApplication::translate("mainWindow", "&PAL", 0, QApplication::UnicodeUTF8));
        action_NTSC->setText(QApplication::translate("mainWindow", "&NTSC", 0, QApplication::UnicodeUTF8));
        action_Dendy->setText(QApplication::translate("mainWindow", "&Dendy", 0, QApplication::UnicodeUTF8));
        action_Mode_Auto->setText(QApplication::translate("mainWindow", "&Auto", 0, QApplication::UnicodeUTF8));
        action_FPS_Default->setText(QApplication::translate("mainWindow", "Default", 0, QApplication::UnicodeUTF8));
        action_FPS_60->setText(QApplication::translate("mainWindow", "60", 0, QApplication::UnicodeUTF8));
        action_FPS_59->setText(QApplication::translate("mainWindow", "59", 0, QApplication::UnicodeUTF8));
        action_FPS_58->setText(QApplication::translate("mainWindow", "58", 0, QApplication::UnicodeUTF8));
        action_FPS_57->setText(QApplication::translate("mainWindow", "57", 0, QApplication::UnicodeUTF8));
        action_FPS_56->setText(QApplication::translate("mainWindow", "56", 0, QApplication::UnicodeUTF8));
        action_FPS_55->setText(QApplication::translate("mainWindow", "55", 0, QApplication::UnicodeUTF8));
        action_FPS_54->setText(QApplication::translate("mainWindow", "54", 0, QApplication::UnicodeUTF8));
        action_FPS_53->setText(QApplication::translate("mainWindow", "53", 0, QApplication::UnicodeUTF8));
        action_FPS_52->setText(QApplication::translate("mainWindow", "52", 0, QApplication::UnicodeUTF8));
        action_FPS_51->setText(QApplication::translate("mainWindow", "51", 0, QApplication::UnicodeUTF8));
        action_FPS_50->setText(QApplication::translate("mainWindow", "50", 0, QApplication::UnicodeUTF8));
        action_FPS_49->setText(QApplication::translate("mainWindow", "49", 0, QApplication::UnicodeUTF8));
        action_FPS_48->setText(QApplication::translate("mainWindow", "48", 0, QApplication::UnicodeUTF8));
        action_FPS_47->setText(QApplication::translate("mainWindow", "47", 0, QApplication::UnicodeUTF8));
        action_FPS_46->setText(QApplication::translate("mainWindow", "46", 0, QApplication::UnicodeUTF8));
        action_FPS_45->setText(QApplication::translate("mainWindow", "45", 0, QApplication::UnicodeUTF8));
        action_FPS_44->setText(QApplication::translate("mainWindow", "44", 0, QApplication::UnicodeUTF8));
        action_Fsk_Default->setText(QApplication::translate("mainWindow", "Default", 0, QApplication::UnicodeUTF8));
        action_Fsk_1->setText(QApplication::translate("mainWindow", "1", 0, QApplication::UnicodeUTF8));
        action_Fsk_2->setText(QApplication::translate("mainWindow", "2", 0, QApplication::UnicodeUTF8));
        action_Fsk_3->setText(QApplication::translate("mainWindow", "3", 0, QApplication::UnicodeUTF8));
        action_Fsk_4->setText(QApplication::translate("mainWindow", "4", 0, QApplication::UnicodeUTF8));
        action_Fsk_5->setText(QApplication::translate("mainWindow", "5", 0, QApplication::UnicodeUTF8));
        action_Fsk_6->setText(QApplication::translate("mainWindow", "6", 0, QApplication::UnicodeUTF8));
        action_Fsk_7->setText(QApplication::translate("mainWindow", "7", 0, QApplication::UnicodeUTF8));
        action_Fsk_8->setText(QApplication::translate("mainWindow", "8", 0, QApplication::UnicodeUTF8));
        action_Fsk_9->setText(QApplication::translate("mainWindow", "9", 0, QApplication::UnicodeUTF8));
        action_Oscan_Default->setText(QApplication::translate("mainWindow", "&Default", 0, QApplication::UnicodeUTF8));
        action_Oscan_On->setText(QApplication::translate("mainWindow", "&On", 0, QApplication::UnicodeUTF8));
        action_Oscan_Off->setText(QApplication::translate("mainWindow", "O&ff", 0, QApplication::UnicodeUTF8));
        action_Oscan_Def_On->setText(QApplication::translate("mainWindow", "&On", 0, QApplication::UnicodeUTF8));
        action_Oscan_Def_Off->setText(QApplication::translate("mainWindow", "O&ff", 0, QApplication::UnicodeUTF8));
        action_Oscan_Set_Borders->setText(QApplication::translate("mainWindow", "&Set borders", 0, QApplication::UnicodeUTF8));
        action_No_Filter->setText(QApplication::translate("mainWindow", "&No Filter", 0, QApplication::UnicodeUTF8));
        action_Phosphor->setText(QApplication::translate("mainWindow", "&Phosphor", 0, QApplication::UnicodeUTF8));
        action_Phosphor2->setText(QApplication::translate("mainWindow", "P&hosphor2", 0, QApplication::UnicodeUTF8));
        action_Scanline->setText(QApplication::translate("mainWindow", "S&canline", 0, QApplication::UnicodeUTF8));
        action_DBL->setText(QApplication::translate("mainWindow", "&DBL", 0, QApplication::UnicodeUTF8));
        action_Dark_Room->setText(QApplication::translate("mainWindow", "Dark R&oom", 0, QApplication::UnicodeUTF8));
        action_CRT_With_Curve->setText(QApplication::translate("mainWindow", "CRT With &Curve", 0, QApplication::UnicodeUTF8));
        action_CRT_Without_Curve->setText(QApplication::translate("mainWindow", "CRT &Without Curve", 0, QApplication::UnicodeUTF8));
        action_Scale2X->setText(QApplication::translate("mainWindow", "Scale&2X", 0, QApplication::UnicodeUTF8));
        action_Scale3X->setText(QApplication::translate("mainWindow", "Scale&3X", 0, QApplication::UnicodeUTF8));
        action_Scale4X->setText(QApplication::translate("mainWindow", "Scale&4X", 0, QApplication::UnicodeUTF8));
        action_Hq2X->setText(QApplication::translate("mainWindow", "Hq&2X", 0, QApplication::UnicodeUTF8));
        action_Hq3X->setText(QApplication::translate("mainWindow", "Hq&3X", 0, QApplication::UnicodeUTF8));
        action_Hq4X->setText(QApplication::translate("mainWindow", "Hq&4X", 0, QApplication::UnicodeUTF8));
        action_xBRZ_2X->setText(QApplication::translate("mainWindow", "xBRZ &2X", 0, QApplication::UnicodeUTF8));
        action_xBRZ_3X->setText(QApplication::translate("mainWindow", "xBRZ &3X", 0, QApplication::UnicodeUTF8));
        action_xBRZ_4X->setText(QApplication::translate("mainWindow", "xBRZ &4X", 0, QApplication::UnicodeUTF8));
        action_NTSC_Composite->setText(QApplication::translate("mainWindow", "NTSC &Composite", 0, QApplication::UnicodeUTF8));
        action_NTSC_SVideo->setText(QApplication::translate("mainWindow", "NTSC &S-Video", 0, QApplication::UnicodeUTF8));
        action_NTSC_RGB->setText(QApplication::translate("mainWindow", "NTSC &RGB", 0, QApplication::UnicodeUTF8));
        action_Palette_PAL->setText(QApplication::translate("mainWindow", "&PAL", 0, QApplication::UnicodeUTF8));
        action_Palette_NTSC->setText(QApplication::translate("mainWindow", "&NTSC", 0, QApplication::UnicodeUTF8));
        action_Sony_CXA2025AS_US->setText(QApplication::translate("mainWindow", "S&ony CXA2025AS US", 0, QApplication::UnicodeUTF8));
        action_Monochrome->setText(QApplication::translate("mainWindow", "&Monochrome", 0, QApplication::UnicodeUTF8));
        action_Green->setText(QApplication::translate("mainWindow", "&Green", 0, QApplication::UnicodeUTF8));
        action_Palette_Save_File->setText(QApplication::translate("mainWindow", "&Save to file", 0, QApplication::UnicodeUTF8));
        action_Palette_Load_File->setText(QApplication::translate("mainWindow", "&Load from file", 0, QApplication::UnicodeUTF8));
        actionShaders->setText(QApplication::translate("mainWindow", "Shaders", 0, QApplication::UnicodeUTF8));
        action_Cube->setText(QApplication::translate("mainWindow", "&Cube", 0, QApplication::UnicodeUTF8));
        action_VSync->setText(QApplication::translate("mainWindow", "&VSync", 0, QApplication::UnicodeUTF8));
        action_Interpolation->setText(QApplication::translate("mainWindow", "&Interpolation", 0, QApplication::UnicodeUTF8));
        action_Text_on_screen->setText(QApplication::translate("mainWindow", "Te&xt on screen", 0, QApplication::UnicodeUTF8));
        action_Fullscreen->setText(QApplication::translate("mainWindow", "F&ullscreen", 0, QApplication::UnicodeUTF8));
        action_Stretch_in_fullscreen->setText(QApplication::translate("mainWindow", "S&tretch in fullscreen", 0, QApplication::UnicodeUTF8));
        action_Sample_rate_44100->setText(QApplication::translate("mainWindow", "&44100", 0, QApplication::UnicodeUTF8));
        action_Sample_rate_48000->setText(QApplication::translate("mainWindow", "4&8000", 0, QApplication::UnicodeUTF8));
        action_Sample_rate_22050->setText(QApplication::translate("mainWindow", "&22050", 0, QApplication::UnicodeUTF8));
        action_Sample_rate_11025->setText(QApplication::translate("mainWindow", "&11025", 0, QApplication::UnicodeUTF8));
        action_Mono->setText(QApplication::translate("mainWindow", "&Mono", 0, QApplication::UnicodeUTF8));
        action_Stereo->setText(QApplication::translate("mainWindow", "&Stereo", 0, QApplication::UnicodeUTF8));
        action_Stereo_delay_5->setText(QApplication::translate("mainWindow", "5%", 0, QApplication::UnicodeUTF8));
        action_Stereo_delay_10->setText(QApplication::translate("mainWindow", "10%", 0, QApplication::UnicodeUTF8));
        action_Stereo_delay_15->setText(QApplication::translate("mainWindow", "15%", 0, QApplication::UnicodeUTF8));
        action_Stereo_delay_20->setText(QApplication::translate("mainWindow", "20%", 0, QApplication::UnicodeUTF8));
        action_Stereo_delay_25->setText(QApplication::translate("mainWindow", "25%", 0, QApplication::UnicodeUTF8));
        action_Stereo_delay_30->setText(QApplication::translate("mainWindow", "30% (Default)", 0, QApplication::UnicodeUTF8));
        action_Stereo_delay_35->setText(QApplication::translate("mainWindow", "35%", 0, QApplication::UnicodeUTF8));
        action_Stereo_delay_40->setText(QApplication::translate("mainWindow", "40%", 0, QApplication::UnicodeUTF8));
        action_Stereo_delay_45->setText(QApplication::translate("mainWindow", "45%", 0, QApplication::UnicodeUTF8));
        action_Stereo_delay_50->setText(QApplication::translate("mainWindow", "50%", 0, QApplication::UnicodeUTF8));
        action_Stereo_delay_55->setText(QApplication::translate("mainWindow", "55%", 0, QApplication::UnicodeUTF8));
        action_Stereo_delay_60->setText(QApplication::translate("mainWindow", "60%", 0, QApplication::UnicodeUTF8));
        action_Stereo_delay_65->setText(QApplication::translate("mainWindow", "65%", 0, QApplication::UnicodeUTF8));
        action_Stereo_delay_70->setText(QApplication::translate("mainWindow", "70%", 0, QApplication::UnicodeUTF8));
        action_Stereo_delay_75->setText(QApplication::translate("mainWindow", "75%", 0, QApplication::UnicodeUTF8));
        action_Stereo_delay_80->setText(QApplication::translate("mainWindow", "80%", 0, QApplication::UnicodeUTF8));
        action_Stereo_delay_85->setText(QApplication::translate("mainWindow", "85%", 0, QApplication::UnicodeUTF8));
        action_Stereo_delay_90->setText(QApplication::translate("mainWindow", "90%", 0, QApplication::UnicodeUTF8));
        action_Stereo_delay_95->setText(QApplication::translate("mainWindow", "95%", 0, QApplication::UnicodeUTF8));
        action_Stereo_delay_100->setText(QApplication::translate("mainWindow", "100%", 0, QApplication::UnicodeUTF8));
        action_Audio_Quality_Low->setText(QApplication::translate("mainWindow", "&Low", 0, QApplication::UnicodeUTF8));
        action_Audio_Quality_High->setText(QApplication::translate("mainWindow", "&High", 0, QApplication::UnicodeUTF8));
        action_APU_channels->setText(QApplication::translate("mainWindow", "A&PU channels", 0, QApplication::UnicodeUTF8));
        action_Swap_Duty_Cycles->setText(QApplication::translate("mainWindow", "S&wap Duty Cycles", 0, QApplication::UnicodeUTF8));
        action_Audio_Enable->setText(QApplication::translate("mainWindow", "&Enable", 0, QApplication::UnicodeUTF8));
        action_Input_Config->setText(QApplication::translate("mainWindow", "&Config", 0, QApplication::UnicodeUTF8));
        action_Pause_when_in_background->setText(QApplication::translate("mainWindow", "Pause when &in background", 0, QApplication::UnicodeUTF8));
        action_Game_Genie->setText(QApplication::translate("mainWindow", "&Game Genie", 0, QApplication::UnicodeUTF8));
        action_Save_settings->setText(QApplication::translate("mainWindow", "Save se&ttings", 0, QApplication::UnicodeUTF8));
        action_Save_settings_on_exit->setText(QApplication::translate("mainWindow", "Save settings on e&xit", 0, QApplication::UnicodeUTF8));
        action_Save_state->setText(QApplication::translate("mainWindow", "&Save state", 0, QApplication::UnicodeUTF8));
        action_Load_state->setText(QApplication::translate("mainWindow", "&Load state", 0, QApplication::UnicodeUTF8));
        action_Increment_slot->setText(QApplication::translate("mainWindow", "&Increment slot", 0, QApplication::UnicodeUTF8));
        action_Decrement_slot->setText(QApplication::translate("mainWindow", "&Decrement slot", 0, QApplication::UnicodeUTF8));
        action_State_Slot_0->setText(QApplication::translate("mainWindow", "Slot &0", 0, QApplication::UnicodeUTF8));
        action_State_Slot_1->setText(QApplication::translate("mainWindow", "Slot &1", 0, QApplication::UnicodeUTF8));
        action_State_Slot_2->setText(QApplication::translate("mainWindow", "Slot &2", 0, QApplication::UnicodeUTF8));
        action_State_Slot_3->setText(QApplication::translate("mainWindow", "Slot &3", 0, QApplication::UnicodeUTF8));
        action_State_Slot_4->setText(QApplication::translate("mainWindow", "Slot &4", 0, QApplication::UnicodeUTF8));
        action_State_Slot_5->setText(QApplication::translate("mainWindow", "Slot &5", 0, QApplication::UnicodeUTF8));
        action_About->setText(QApplication::translate("mainWindow", "&About", 0, QApplication::UnicodeUTF8));
        menu_File->setTitle(QApplication::translate("mainWindow", "&File", 0, QApplication::UnicodeUTF8));
        menu_Recent_Roms->setTitle(QApplication::translate("mainWindow", "&Recent Roms", 0, QApplication::UnicodeUTF8));
        menu_NES->setTitle(QApplication::translate("mainWindow", "&NES", 0, QApplication::UnicodeUTF8));
        menu_Disk_Side->setTitle(QApplication::translate("mainWindow", "&Disk Side", 0, QApplication::UnicodeUTF8));
        menu_Settings->setTitle(QApplication::translate("mainWindow", "&Settings", 0, QApplication::UnicodeUTF8));
        menu_Mode->setTitle(QApplication::translate("mainWindow", "&Mode", 0, QApplication::UnicodeUTF8));
        menu_Video->setTitle(QApplication::translate("mainWindow", "&Video", 0, QApplication::UnicodeUTF8));
        menu_Rendering->setTitle(QApplication::translate("mainWindow", "&Rendering", 0, QApplication::UnicodeUTF8));
        menu_FPS->setTitle(QApplication::translate("mainWindow", "&FPS", 0, QApplication::UnicodeUTF8));
        menu_Frame_skip->setTitle(QApplication::translate("mainWindow", "Fra&me skip", 0, QApplication::UnicodeUTF8));
        menu_Scale->setTitle(QApplication::translate("mainWindow", "&Scale", 0, QApplication::UnicodeUTF8));
        menu_Pixel_Aspect_Ratio->setTitle(QApplication::translate("mainWindow", "Pixel Aspect Ra&tio", 0, QApplication::UnicodeUTF8));
        menu_Overscan->setTitle(QApplication::translate("mainWindow", "&Overscan", 0, QApplication::UnicodeUTF8));
        menu_Oscan_Default_Value->setTitle(QApplication::translate("mainWindow", "De&fault value", 0, QApplication::UnicodeUTF8));
        menu_Filter->setTitle(QApplication::translate("mainWindow", "Fi&lter", 0, QApplication::UnicodeUTF8));
        menu_Palette->setTitle(QApplication::translate("mainWindow", "&Palette", 0, QApplication::UnicodeUTF8));
        menu_Effect->setTitle(QApplication::translate("mainWindow", "&Effect", 0, QApplication::UnicodeUTF8));
        menu_Audio->setTitle(QApplication::translate("mainWindow", "&Audio", 0, QApplication::UnicodeUTF8));
        menu_Sample_rate->setTitle(QApplication::translate("mainWindow", "&Sample rate", 0, QApplication::UnicodeUTF8));
        menu_Channels->setTitle(QApplication::translate("mainWindow", "&Channels", 0, QApplication::UnicodeUTF8));
        menu_Stereo_delay->setTitle(QApplication::translate("mainWindow", "S&tereo delay", 0, QApplication::UnicodeUTF8));
        menu_Audio_Quality->setTitle(QApplication::translate("mainWindow", "&Quality", 0, QApplication::UnicodeUTF8));
        menu_Input->setTitle(QApplication::translate("mainWindow", "&Input", 0, QApplication::UnicodeUTF8));
        menu_State->setTitle(QApplication::translate("mainWindow", "S&tate", 0, QApplication::UnicodeUTF8));
        menu_Help->setTitle(QApplication::translate("mainWindow", "&Help", 0, QApplication::UnicodeUTF8));
        Q_UNUSED(mainWindow);
    } // retranslateUi

};

namespace Ui {
    class mainWindow: public Ui_mainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // APPLICATION_H
