name: release-macos

on:
  release:
    tags:
      - '*'

jobs:
  macos:
    name: macos-binary
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: build 7za & test
        run: |
             cp makefile.macosx_gcc_64bits makefile.machine
             make 7za
             cd ./bin
             ./7za a ta.7z ../CPP
             ./7za x ta.7z
             echo "compare file"
             diff -r ../CPP ./CPP
             echo "delete tmp file"
             rm -rf ./ta.7z ./CPP
             cd ..

      - name: build 7zr & test
        run: |
             make 7zr
             cd ./bin
             ./7zr a tr.7z ../CPP
             ./7zr x tr.7z
             echo "compare file"
             diff -r ../CPP ./CPP
             echo "delete tmp file"
             rm -rf ./tr.7z ./CPP
             cd ..

      - name: build 7z & test
        run: |
             make 7z
             cd ./bin
             ./7z a t.7z ../CPP
             ./7z x t.7z
             echo "compare file"
             diff -r ../CPP ./CPP
             echo "delete tmp file"
             rm -rf ./t.7z ./CPP
             cd ..

      - name: build sfx
        run: |
             make sfx

      - name: check
        run: |
             cd ./check
             bash check.sh `pwd`/../bin/7z
             bash check_7za.sh `pwd`/../bin/7za
             bash check_7zr.sh `pwd`/../bin/7zr
             cd ..
      - name: Get runner environment variables
        id: runner
        uses: techno-express/action-environment-info@1
      - name: Create 7z & Zip binary archive from build
        run: |
             ./bin/7za a ${{ format('macos-{0}-p7zip.7z', steps.runner.outputs.version) }} ./bin/* -t7z -y
             ./bin/7z a ${{ format('macos-{0}-p7zip.zip', steps.runner.outputs.version) }} ./bin/* -tzip -y
      - name: Upload the macOS binary artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ format('macos-{0}-p7zip.*', steps.runner.outputs.version) }}
          asset_name: ${{ format('macos-{0}-p7zip', steps.runner.outputs.version) }}
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          body: "This is macos binary release using make"

  macos-cmake:
    name: macos-cmake-binary
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: cmake build 7z_ & test
        run: |
             cd ./CPP/7zip/CMAKE/
             rm -rf ./build
             mkdir build
             cd build
             cmake ..
             make 7z_
             make 7z
             make Rar
             make 7zCon.sfx
             cd ./bin
             ./7z_ a t_.7z ../../../Archive
             ./7z_ x t_.7z
             echo "compare file"
             diff -r ../../../Archive ./Archive
             echo "delte tmp file"
             rm -rf t_.7z Archive

      - name: cmake build 7za & test
        run: |
             cd ./CPP/7zip/CMAKE/build/
             make 7za
             cd ./bin
             ./7za a ta.7z ../../../Archive
             ./7za x ta.7z
             echo "compare file"
             diff -r ../../../Archive ./Archive
             echo "delete tmp file"
             rm -rf ta.7z Archive

      - name: cmake build 7zr & test
        run: |
             cd ./CPP/7zip/CMAKE/build/
             make 7zr
             cd ./bin
             ./7zr a tr.7z ../../../Archive
             ./7zr x tr.7z
             echo "compare file"
             diff -r ../../../Archive ./Archive
             echo "delete tmp file"
             rm -rf tr.7z Archive

      - name: check
        run: |
             cd ./check
             bash ./check.sh `pwd`/../CPP/7zip/CMAKE/build/bin/7z_
             bash ./check_7za.sh `pwd`/../CPP/7zip/CMAKE/build/bin/7za
             bash ./check_7zr.sh `pwd`/../CPP/7zip/CMAKE/build/bin/7zr
             cd ..
      - name: Get runner environment variables
        id: runner
        uses: techno-express/action-environment-info@1
      - name: Create 7z & Zip binary archive from build
        run: |
             rm -rf ./CPP/7zip/CMAKE/build/bin/Codecs/CMakeFiles
             rm -rf ./CPP/7zip/CMAKE/build/bin/Codecs/Makefile
             rm -rf ./CPP/7zip/CMAKE/build/bin/Codecs/cmake_install.cmake
             ./CPP/7zip/CMAKE/build/bin/7za a ${{ format('macos-{0}-cmake-p7zip.7z', steps.runner.outputs.version) }} ./CPP/7zip/CMAKE/build/bin/7z* ./CPP/7zip/CMAKE/build/bin/Codecs -t7z -y
             ./CPP/7zip/CMAKE/build/bin/7z_ a ${{ format('macos-{0}-cmake-p7zip.zip', steps.runner.outputs.version) }} ./CPP/7zip/CMAKE/build/bin/7z* ./CPP/7zip/CMAKE/build/bin/Codecs -tzip -y
      - name: Upload the cmake macOS binary artifacts
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ format('macos-{0}-cmake-p7zip.*', steps.runner.outputs.version) }}
          asset_name: ${{ format('macos-{0}-cmake-p7zip', steps.runner.outputs.version) }}
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
          body: "This is macos binary release using cmake"
