SRCS=\
 ../../../myWindows/myGetTickCount.cpp \
 ../../../myWindows/wine_date_and_time.cpp \
 ../../../myWindows/mySplitCommandLine.cpp \
 \
 Main.cpp \
 \
 ../../UI/Console/ConsoleClose.cpp \
 ../../UI/Console/ExtractCallbackConsole.cpp \
 ../../UI/Console/List.cpp \
 ../../UI/Console/MainAr.cpp \
 ../../UI/Console/OpenCallbackConsole.cpp \
 ../../UI/Console/UserInputUtils.cpp \
 \
 ../../../Common/CommandLineParser.cpp \
 ../../../Common/CRC.cpp \
 ../../../Common/IntToString.cpp \
 ../../../Common/StdInStream.cpp \
 ../../../Common/StdOutStream.cpp \
 ../../../Common/MyString.cpp \
 ../../../Common/MyWindows.cpp \
 ../../../Common/StringConvert.cpp \
 ../../../Common/UTFConvert.cpp \
 ../../../Common/MyVector.cpp \
 ../../../Common/Wildcard.cpp \
 \
 ../../../Windows/Error.cpp \
 ../../../Windows/FileDir.cpp \
 ../../../Windows/FileFind.cpp \
 ../../../Windows/FileIO.cpp \
 ../../../Windows/FileName.cpp \
 ../../../Windows/PropVariant.cpp \
 ../../../Windows/PropVariantConversions.cpp \
 ../../../Windows/Synchronization.cpp \
 ../../../Windows/System.cpp \
 \
 ../../Common/CreateCoder.cpp \
 ../../Common/CWrappers.cpp \
 ../../Common/FilePathAutoRename.cpp \
 ../../Common/FileStreams.cpp \
 ../../Common/InBuffer.cpp \
 ../../Common/FilterCoder.cpp \
 ../../Common/LimitedStreams.cpp \
 ../../Common/LockedStream.cpp \
 ../../Common/OutBuffer.cpp \
 ../../Common/ProgressUtils.cpp \
 ../../Common/StreamBinder.cpp \
 ../../Common/StreamObjects.cpp \
 ../../Common/StreamUtils.cpp \
 ../../Common/VirtThread.cpp \
 \
 ../../UI/Common/ArchiveExtractCallback.cpp \
 ../../UI/Common/ArchiveOpenCallback.cpp \
 ../../UI/Common/DefaultName.cpp \
 ../../UI/Common/Extract.cpp \
 ../../UI/Common/ExtractingFilePath.cpp \
 ../../UI/Common/LoadCodecs.cpp \
 ../../UI/Common/OpenArchive.cpp \
 ../../UI/Common/PropIDUtils.cpp \
 \
 ../../Archive/Common/CoderMixer2.cpp \
 ../../Archive/Common/CoderMixer2MT.cpp \
 ../../Archive/Common/CrossThreadProgress.cpp \
 ../../Archive/Common/OutStreamWithCRC.cpp \
 \
 ../../Archive/7z/7zDecode.cpp \
 ../../Archive/7z/7zExtract.cpp \
 ../../Archive/7z/7zFolderOutStream.cpp \
 ../../Archive/7z/7zHandler.cpp \
 ../../Archive/7z/7zHeader.cpp \
 ../../Archive/7z/7zIn.cpp \
 ../../Archive/7z/7zRegister.cpp \
 \
 ../../Compress/BranchCoder.cpp \
 ../../Compress/Bcj2Coder.cpp \
 ../../Compress/Bcj2Register.cpp \
 ../../Compress/BcjCoder.cpp \
 ../../Compress/BcjRegister.cpp \
 ../../Compress/LzmaDecoder.cpp \
 ../../Compress/LzmaRegister.cpp \
 ../../Compress/LzmaDecoder.cpp \
 ../../Compress/LzmaRegister.cpp \
 ../../Compress/PpmdDecoder.cpp \
 ../../Compress/PpmdRegister.cpp \
 \
 ../../Crypto/7zAes.cpp \
 ../../Crypto/7zAesRegister.cpp \
 ../../Crypto/MyAes.cpp \

SRCS_C=\
 ../../../../C/Aes.c \
 ../../../../C/Alloc.c \
 ../../../../C/Bra86.c \
 ../../../../C/Lzma2Dec.c \
 ../../../../C/LzmaDec.c \
 ../../../../C/Ppmd7.c \
 ../../../../C/Ppmd7Dec.c \
 ../../../../C/Sha256.c \
 ../../../../C/Threads.c \

include ../../../../makefile.rules

Main.o : Main.cpp
	$(CXX) $(CXXFLAGS) Main.cpp


