################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/mappers/mapper0.c \
../src/mappers/mapper114.c \
../src/mappers/mapper116.c \
../src/mappers/mapper120.c \
../src/mappers/mapper121.c \
../src/mappers/mapper156.c \
../src/mappers/mapper176.c \
../src/mappers/mapper178.c \
../src/mappers/mapper182.c \
../src/mappers/mapper183.c \
../src/mappers/mapper186.c \
../src/mappers/mapper200.c \
../src/mappers/mapper201.c \
../src/mappers/mapper202.c \
../src/mappers/mapper203.c \
../src/mappers/mapper204.c \
../src/mappers/mapper205.c \
../src/mappers/mapper208.c \
../src/mappers/mapper212.c \
../src/mappers/mapper213.c \
../src/mappers/mapper214.c \
../src/mappers/mapper215.c \
../src/mappers/mapper217.c \
../src/mappers/mapper219.c \
../src/mappers/mapper221.c \
../src/mappers/mapper222.c \
../src/mappers/mapper225.c \
../src/mappers/mapper226.c \
../src/mappers/mapper227.c \
../src/mappers/mapper229.c \
../src/mappers/mapper230.c \
../src/mappers/mapper231.c \
../src/mappers/mapper233.c \
../src/mappers/mapper235.c \
../src/mappers/mapper240.c \
../src/mappers/mapper241.c \
../src/mappers/mapper242.c \
../src/mappers/mapper244.c \
../src/mappers/mapper246.c \
../src/mappers/mapper37.c \
../src/mappers/mapper44.c \
../src/mappers/mapper45.c \
../src/mappers/mapper46.c \
../src/mappers/mapper47.c \
../src/mappers/mapper49.c \
../src/mappers/mapper50.c \
../src/mappers/mapper51.c \
../src/mappers/mapper52.c \
../src/mappers/mapper53.c \
../src/mappers/mapper57.c \
../src/mappers/mapper58.c \
../src/mappers/mapper60.c \
../src/mappers/mapper61.c \
../src/mappers/mapper62.c \
../src/mappers/mapper74x138x161.c \
../src/mappers/mapper74x161x161x32.c \
../src/mappers/mapperActive.c \
../src/mappers/mapperAgci.c \
../src/mappers/mapperAve.c \
../src/mappers/mapperAxROM.c \
../src/mappers/mapperBandai.c \
../src/mappers/mapperBxROM.c \
../src/mappers/mapperCNROM.c \
../src/mappers/mapperCPROM.c \
../src/mappers/mapperCaltron.c \
../src/mappers/mapperCamerica.c \
../src/mappers/mapperColorDreams.c \
../src/mappers/mapperFDS.c \
../src/mappers/mapperFuturemedia.c \
../src/mappers/mapperGameGenie.c \
../src/mappers/mapperGxROM.c \
../src/mappers/mapperHen.c \
../src/mappers/mapperHes.c \
../src/mappers/mapperIrem.c \
../src/mappers/mapperJaleco.c \
../src/mappers/mapperKaiser.c \
../src/mappers/mapperKasing.c \
../src/mappers/mapperMMC1.c \
../src/mappers/mapperMMC2andMMC4.c \
../src/mappers/mapperMMC3.c \
../src/mappers/mapperMMC5.c \
../src/mappers/mapperMagic.c \
../src/mappers/mapperNamco.c \
../src/mappers/mapperNtdec.c \
../src/mappers/mapperRcm.c \
../src/mappers/mapperRex.c \
../src/mappers/mapperSachen.c \
../src/mappers/mapperSunsoft.c \
../src/mappers/mapperTaito.c \
../src/mappers/mapperTengen.c \
../src/mappers/mapperTxROM.c \
../src/mappers/mapperTxc.c \
../src/mappers/mapperUxROM.c \
../src/mappers/mapperVRC1.c \
../src/mappers/mapperVRC2.c \
../src/mappers/mapperVRC3.c \
../src/mappers/mapperVRC4.c \
../src/mappers/mapperVRC6.c \
../src/mappers/mapperVRC7.c \
../src/mappers/mapperVRC7snd.c \
../src/mappers/mapperVs.c \
../src/mappers/mapperWaixing.c \
../src/mappers/mapperWhirlwind.c 

OBJS += \
./src/mappers/mapper0.o \
./src/mappers/mapper114.o \
./src/mappers/mapper116.o \
./src/mappers/mapper120.o \
./src/mappers/mapper121.o \
./src/mappers/mapper156.o \
./src/mappers/mapper176.o \
./src/mappers/mapper178.o \
./src/mappers/mapper182.o \
./src/mappers/mapper183.o \
./src/mappers/mapper186.o \
./src/mappers/mapper200.o \
./src/mappers/mapper201.o \
./src/mappers/mapper202.o \
./src/mappers/mapper203.o \
./src/mappers/mapper204.o \
./src/mappers/mapper205.o \
./src/mappers/mapper208.o \
./src/mappers/mapper212.o \
./src/mappers/mapper213.o \
./src/mappers/mapper214.o \
./src/mappers/mapper215.o \
./src/mappers/mapper217.o \
./src/mappers/mapper219.o \
./src/mappers/mapper221.o \
./src/mappers/mapper222.o \
./src/mappers/mapper225.o \
./src/mappers/mapper226.o \
./src/mappers/mapper227.o \
./src/mappers/mapper229.o \
./src/mappers/mapper230.o \
./src/mappers/mapper231.o \
./src/mappers/mapper233.o \
./src/mappers/mapper235.o \
./src/mappers/mapper240.o \
./src/mappers/mapper241.o \
./src/mappers/mapper242.o \
./src/mappers/mapper244.o \
./src/mappers/mapper246.o \
./src/mappers/mapper37.o \
./src/mappers/mapper44.o \
./src/mappers/mapper45.o \
./src/mappers/mapper46.o \
./src/mappers/mapper47.o \
./src/mappers/mapper49.o \
./src/mappers/mapper50.o \
./src/mappers/mapper51.o \
./src/mappers/mapper52.o \
./src/mappers/mapper53.o \
./src/mappers/mapper57.o \
./src/mappers/mapper58.o \
./src/mappers/mapper60.o \
./src/mappers/mapper61.o \
./src/mappers/mapper62.o \
./src/mappers/mapper74x138x161.o \
./src/mappers/mapper74x161x161x32.o \
./src/mappers/mapperActive.o \
./src/mappers/mapperAgci.o \
./src/mappers/mapperAve.o \
./src/mappers/mapperAxROM.o \
./src/mappers/mapperBandai.o \
./src/mappers/mapperBxROM.o \
./src/mappers/mapperCNROM.o \
./src/mappers/mapperCPROM.o \
./src/mappers/mapperCaltron.o \
./src/mappers/mapperCamerica.o \
./src/mappers/mapperColorDreams.o \
./src/mappers/mapperFDS.o \
./src/mappers/mapperFuturemedia.o \
./src/mappers/mapperGameGenie.o \
./src/mappers/mapperGxROM.o \
./src/mappers/mapperHen.o \
./src/mappers/mapperHes.o \
./src/mappers/mapperIrem.o \
./src/mappers/mapperJaleco.o \
./src/mappers/mapperKaiser.o \
./src/mappers/mapperKasing.o \
./src/mappers/mapperMMC1.o \
./src/mappers/mapperMMC2andMMC4.o \
./src/mappers/mapperMMC3.o \
./src/mappers/mapperMMC5.o \
./src/mappers/mapperMagic.o \
./src/mappers/mapperNamco.o \
./src/mappers/mapperNtdec.o \
./src/mappers/mapperRcm.o \
./src/mappers/mapperRex.o \
./src/mappers/mapperSachen.o \
./src/mappers/mapperSunsoft.o \
./src/mappers/mapperTaito.o \
./src/mappers/mapperTengen.o \
./src/mappers/mapperTxROM.o \
./src/mappers/mapperTxc.o \
./src/mappers/mapperUxROM.o \
./src/mappers/mapperVRC1.o \
./src/mappers/mapperVRC2.o \
./src/mappers/mapperVRC3.o \
./src/mappers/mapperVRC4.o \
./src/mappers/mapperVRC6.o \
./src/mappers/mapperVRC7.o \
./src/mappers/mapperVRC7snd.o \
./src/mappers/mapperVs.o \
./src/mappers/mapperWaixing.o \
./src/mappers/mapperWhirlwind.o 

C_DEPS += \
./src/mappers/mapper0.d \
./src/mappers/mapper114.d \
./src/mappers/mapper116.d \
./src/mappers/mapper120.d \
./src/mappers/mapper121.d \
./src/mappers/mapper156.d \
./src/mappers/mapper176.d \
./src/mappers/mapper178.d \
./src/mappers/mapper182.d \
./src/mappers/mapper183.d \
./src/mappers/mapper186.d \
./src/mappers/mapper200.d \
./src/mappers/mapper201.d \
./src/mappers/mapper202.d \
./src/mappers/mapper203.d \
./src/mappers/mapper204.d \
./src/mappers/mapper205.d \
./src/mappers/mapper208.d \
./src/mappers/mapper212.d \
./src/mappers/mapper213.d \
./src/mappers/mapper214.d \
./src/mappers/mapper215.d \
./src/mappers/mapper217.d \
./src/mappers/mapper219.d \
./src/mappers/mapper221.d \
./src/mappers/mapper222.d \
./src/mappers/mapper225.d \
./src/mappers/mapper226.d \
./src/mappers/mapper227.d \
./src/mappers/mapper229.d \
./src/mappers/mapper230.d \
./src/mappers/mapper231.d \
./src/mappers/mapper233.d \
./src/mappers/mapper235.d \
./src/mappers/mapper240.d \
./src/mappers/mapper241.d \
./src/mappers/mapper242.d \
./src/mappers/mapper244.d \
./src/mappers/mapper246.d \
./src/mappers/mapper37.d \
./src/mappers/mapper44.d \
./src/mappers/mapper45.d \
./src/mappers/mapper46.d \
./src/mappers/mapper47.d \
./src/mappers/mapper49.d \
./src/mappers/mapper50.d \
./src/mappers/mapper51.d \
./src/mappers/mapper52.d \
./src/mappers/mapper53.d \
./src/mappers/mapper57.d \
./src/mappers/mapper58.d \
./src/mappers/mapper60.d \
./src/mappers/mapper61.d \
./src/mappers/mapper62.d \
./src/mappers/mapper74x138x161.d \
./src/mappers/mapper74x161x161x32.d \
./src/mappers/mapperActive.d \
./src/mappers/mapperAgci.d \
./src/mappers/mapperAve.d \
./src/mappers/mapperAxROM.d \
./src/mappers/mapperBandai.d \
./src/mappers/mapperBxROM.d \
./src/mappers/mapperCNROM.d \
./src/mappers/mapperCPROM.d \
./src/mappers/mapperCaltron.d \
./src/mappers/mapperCamerica.d \
./src/mappers/mapperColorDreams.d \
./src/mappers/mapperFDS.d \
./src/mappers/mapperFuturemedia.d \
./src/mappers/mapperGameGenie.d \
./src/mappers/mapperGxROM.d \
./src/mappers/mapperHen.d \
./src/mappers/mapperHes.d \
./src/mappers/mapperIrem.d \
./src/mappers/mapperJaleco.d \
./src/mappers/mapperKaiser.d \
./src/mappers/mapperKasing.d \
./src/mappers/mapperMMC1.d \
./src/mappers/mapperMMC2andMMC4.d \
./src/mappers/mapperMMC3.d \
./src/mappers/mapperMMC5.d \
./src/mappers/mapperMagic.d \
./src/mappers/mapperNamco.d \
./src/mappers/mapperNtdec.d \
./src/mappers/mapperRcm.d \
./src/mappers/mapperRex.d \
./src/mappers/mapperSachen.d \
./src/mappers/mapperSunsoft.d \
./src/mappers/mapperTaito.d \
./src/mappers/mapperTengen.d \
./src/mappers/mapperTxROM.d \
./src/mappers/mapperTxc.d \
./src/mappers/mapperUxROM.d \
./src/mappers/mapperVRC1.d \
./src/mappers/mapperVRC2.d \
./src/mappers/mapperVRC3.d \
./src/mappers/mapperVRC4.d \
./src/mappers/mapperVRC6.d \
./src/mappers/mapperVRC7.d \
./src/mappers/mapperVRC7snd.d \
./src/mappers/mapperVs.d \
./src/mappers/mapperWaixing.d \
./src/mappers/mapperWhirlwind.d 


# Each subdirectory must supply rules for building sources it contributes
src/mappers/%.o: ../src/mappers/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Compiler'
	gcc -DOPENGL -DGTK -DGLEW_STATIC -I../src -I/usr/include/SDL -O3 -Wall -ffast-math -msse2 -mfpmath=sse -c -fmessage-length=0 -finline-functions -Winline `pkg-config --libs --cflags gtk+-2.0` -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


