{
"#pragma parameter mixfactor \"Motionblur Fadeout\" 0.75 0.0 1.0 0.01\n"
"#ifdef PARAMETER_UNIFORM\n"
"uniform float mixfactor;\n"
"#else\n"
"#define mixfactor 0.75\n"
"#endif\n"
"\n"
"struct input\n"
"{\n"
"float2 tex_coord;\n"
"float4 vertex_coord;\n"
"uniform float4x4 mvp_matrix;\n"
"uniform sampler2D texture;\n"
"};\n"
"\n"
"struct vertex_data\n"
"{\n"
"float2 tex;\n"
"float2 feedback_tex;\n"
"};\n"
"\n"
"void main_vertex\n"
"(\n"
"input IN,\n"
"input FEEDBACK,\n"
"out float4 oPosition : POSITION,\n"
"out vertex_data vert\n"
")\n"
"{\n"
"oPosition = mul(IN.mvp_matrix, IN.vertex_coord);\n"
"vert = vertex_data(IN.tex_coord, FEEDBACK.tex_coord);\n"
"}\n"
"\n"
"float4 main_fragment(in vertex_data vert, input IN, input FEEDBACK) : COLOR\n"
"{\n"
"float4 current = pow(tex2D(IN.texture, vert.tex).rgba, float4(2.2));\n"
"float4 fdback = pow(tex2D(FEEDBACK.texture, vert.feedback_tex).rgba, float4(2.2));\n"
"float4 mixed = (1.0 - mixfactor) * current + mixfactor * fdback;\n"
"return pow(mixed, float4(1.0 / 2.2));\n"
"}\n"
},
