"\n"
"// #define compositeConnection\n"
"// #define noScanlines\n"
"\n"
"#define signalResolution		256.0\n"
"#define signalResolutionI		83.0\n"
"#define signalResolutionQ		25.0\n"
"#define tvVerticalResolution	250.0\n"
"\n"
"#define blackLevel 0.0875\n"
"#define contrast 1.0\n"
"\n"
"#define FIXNUM 6\n"
