{
"#pragma parameter GAMMA_INPUT \"Gamma Input\" 2.4 0.1 5.0 0.01\n"
"\n"
"#ifdef PARAMETER_UNIFORM\n"
"uniform float GAMMA_INPUT;\n"
"#else\n"
"#define GAMMA_INPUT 2.4\n"
"#endif\n"
"\n"
"void main_vertex\n"
"(\n"
"    float4 position : POSITION,\n"
"    out float4 oPosition : POSITION,\n"
"    uniform float4x4 modelViewProj,\n"
"\n"
"    float2 tex : TEXCOORD,\n"
"    out float2 oTex : TEXCOORD\n"
")\n"
"{\n"
"    oPosition = mul(modelViewProj, position);\n"
"    oTex = tex;\n"
"}\n"
"\n"
"float4 main_fragment(uniform sampler2D tex : TEXUNIT0, float2 coords : TEXCOORD0) : COLOR\n"
"{\n"
"    return pow(tex2D(tex, coords), GAMMA_INPUT);\n"
"}\n"
},
