{
"void main_vertex\n"
"(\n"
"    float4 position : POSITION,\n"
"    out float4 oPosition : POSITION,\n"
"    uniform float4x4 modelViewProj,\n"
"\n"
"    float2 tex : TEXCOORD,\n"
"    out float2 oTex : TEXCOORD\n"
")\n"
"{\n"
"    oPosition = mul(modelViewProj, position);\n"
"    oTex = tex;\n"
"}\n"
"\n"
"struct input\n"
"{\n"
"    float2 video_size;\n"
"    float2 texture_size;\n"
"    float2 output_size;\n"
"    float frame_count;\n"
"    float frame_direction;\n"
"    float frame_rotation;\n"
"};\n"
"\n"
"struct prev\n"
"{\n"
"    sampler2D texture : TEXUNIT1;\n"
"};\n"
"\n"
"float4 main_fragment(uniform sampler2D tex : TEXUNIT0, float2 coords : TEXCOORD0, uniform input IN, uniform prev PASSPREV3) : COLOR\n"
"{\n"
"    float3 diff = saturate(tex2D(tex, coords).rgb - tex2D(PASSPREV3.texture, coords).rgb);\n"
"\n"
"    return float4(diff, 1.0);\n"
"}\n"
},
