/*
 *  Copyright (C) 2010-2023 Fabio Cavallo (aka FHorse)
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#ifndef MAPPERS_H_
#define MAPPERS_H_

#include "common.h"
#include "external_calls.h"
#include "unif.h"
#include "mappers/mapper_NSF.h"
// INES/NES2.0

#include "mappers/mapper_000.h"
#include "mappers/mapper_001.h"
#include "mappers/mapper_004.h"
#include "mappers/mapper_009.h"
#include "mappers/mapper_010.h"
#include "mappers/mapper_014.h"
#include "mappers/mapper_015.h"
#include "mappers/mapper_019.h"
#include "mappers/mapper_021.h"
#include "mappers/mapper_022.h"
#include "mappers/mapper_023.h"
#include "mappers/mapper_024.h"
#include "mappers/mapper_025.h"
#include "mappers/mapper_026.h"
#include "mappers/mapper_028.h"
#include "mappers/mapper_029.h"
#include "mappers/mapper_031.h"
#include "mappers/mapper_036.h"
#include "mappers/mapper_037.h"
#include "mappers/mapper_038.h"
#include "mappers/mapper_040.h"
#include "mappers/mapper_042.h"
#include "mappers/mapper_043.h"
#include "mappers/mapper_044.h"
#include "mappers/mapper_045.h"
#include "mappers/mapper_046.h"
#include "mappers/mapper_047.h"
#include "mappers/mapper_049.h"
#include "mappers/mapper_050.h"
#include "mappers/mapper_051.h"
#include "mappers/mapper_052.h"
#include "mappers/mapper_053.h"
#include "mappers/mapper_057.h"
#include "mappers/mapper_058.h"
#include "mappers/mapper_059.h"
#include "mappers/mapper_060.h"
#include "mappers/mapper_061.h"
#include "mappers/mapper_062.h"
#include "mappers/mapper_063.h"
#include "mappers/mapper_067.h"
#include "mappers/mapper_068.h"
#include "mappers/mapper_069.h"
#include "mappers/mapper_070.h"
#include "mappers/mapper_074.h"
#include "mappers/mapper_076.h"
#include "mappers/mapper_081.h"
#include "mappers/mapper_083.h"
#include "mappers/mapper_085.h"
#include "mappers/mapper_088.h"
#include "mappers/mapper_089.h"
#include "mappers/mapper_091.h"
#include "mappers/mapper_093.h"
#include "mappers/mapper_095.h"
#include "mappers/mapper_100.h"
#include "mappers/mapper_101.h"
#include "mappers/mapper_103.h"
#include "mappers/mapper_105.h"
#include "mappers/mapper_106.h"
#include "mappers/mapper_108.h"
#include "mappers/mapper_111.h"
#include "mappers/mapper_114.h"
#include "mappers/mapper_115.h"
#include "mappers/mapper_116.h"
#include "mappers/mapper_117.h"
#include "mappers/mapper_119.h"
#include "mappers/mapper_120.h"
#include "mappers/mapper_121.h"
#include "mappers/mapper_123.h"
#include "mappers/mapper_126.h"
#include "mappers/mapper_134.h"
#include "mappers/mapper_152.h"
#include "mappers/mapper_154.h"
#include "mappers/mapper_156.h"
#include "mappers/mapper_163.h"
#include "mappers/mapper_164.h"
#include "mappers/mapper_165.h"
#include "mappers/mapper_166.h"
#include "mappers/mapper_167.h"
#include "mappers/mapper_168.h"
#include "mappers/mapper_178.h"
#include "mappers/mapper_182.h"
#include "mappers/mapper_183.h"
#include "mappers/mapper_184.h"
#include "mappers/mapper_185.h"
#include "mappers/mapper_186.h"
#include "mappers/mapper_187.h"
#include "mappers/mapper_188.h"
#include "mappers/mapper_189.h"
#include "mappers/mapper_190.h"
#include "mappers/mapper_191.h"
#include "mappers/mapper_192.h"
#include "mappers/mapper_194.h"
#include "mappers/mapper_195.h"
#include "mappers/mapper_196.h"
#include "mappers/mapper_197.h"
#include "mappers/mapper_198.h"
#include "mappers/mapper_199.h"
#include "mappers/mapper_200.h"
#include "mappers/mapper_201.h"
#include "mappers/mapper_202.h"
#include "mappers/mapper_203.h"
#include "mappers/mapper_204.h"
#include "mappers/mapper_205.h"
#include "mappers/mapper_206.h"
#include "mappers/mapper_208.h"
#include "mappers/mapper_210.h"
#include "mappers/mapper_212.h"
#include "mappers/mapper_213.h"
#include "mappers/mapper_214.h"
#include "mappers/mapper_215.h"
#include "mappers/mapper_217.h"
#include "mappers/mapper_218.h"
#include "mappers/mapper_219.h"
#include "mappers/mapper_221.h"
#include "mappers/mapper_222.h"
#include "mappers/mapper_225.h"
#include "mappers/mapper_226.h"
#include "mappers/mapper_227.h"
#include "mappers/mapper_229.h"
#include "mappers/mapper_230.h"
#include "mappers/mapper_231.h"
#include "mappers/mapper_235.h"
#include "mappers/mapper_237.h"
#include "mappers/mapper_238.h"
#include "mappers/mapper_240.h"
#include "mappers/mapper_241.h"
#include "mappers/mapper_242.h"
#include "mappers/mapper_244.h"
#include "mappers/mapper_245.h"
#include "mappers/mapper_246.h"
#include "mappers/mapper_249.h"
#include "mappers/mapper_250.h"
#include "mappers/mapper_252.h"
#include "mappers/mapper_254.h"
#include "mappers/mapper_256.h"
#include "mappers/mapper_259.h"
#include "mappers/mapper_260.h"
#include "mappers/mapper_262.h"
#include "mappers/mapper_263.h"
#include "mappers/mapper_266.h"
#include "mappers/mapper_267.h"
#include "mappers/mapper_269.h"
#include "mappers/mapper_271.h"
#include "mappers/mapper_274.h"
#include "mappers/mapper_287.h"
#include "mappers/mapper_288.h"
#include "mappers/mapper_289.h"
#include "mappers/mapper_291.h"
#include "mappers/mapper_292.h"
#include "mappers/mapper_297.h"
#include "mappers/mapper_298.h"
#include "mappers/mapper_299.h"
#include "mappers/mapper_300.h"
#include "mappers/mapper_302.h"
#include "mappers/mapper_307.h"
#include "mappers/mapper_308.h"
#include "mappers/mapper_311.h"
#include "mappers/mapper_313.h"
#include "mappers/mapper_315.h"
#include "mappers/mapper_322.h"
#include "mappers/mapper_323.h"
#include "mappers/mapper_325.h"
#include "mappers/mapper_327.h"
#include "mappers/mapper_331.h"
#include "mappers/mapper_333.h"
#include "mappers/mapper_334.h"
#include "mappers/mapper_337.h"
#include "mappers/mapper_339.h"
#include "mappers/mapper_344.h"
#include "mappers/mapper_345.h"
#include "mappers/mapper_348.h"
#include "mappers/mapper_351.h"
#include "mappers/mapper_353.h"
#include "mappers/mapper_355.h"
#include "mappers/mapper_356.h"
#include "mappers/mapper_357.h"
#include "mappers/mapper_359.h"
#include "mappers/mapper_360.h"
#include "mappers/mapper_361.h"
#include "mappers/mapper_362.h"
#include "mappers/mapper_366.h"
#include "mappers/mapper_368.h"
#include "mappers/mapper_369.h"
#include "mappers/mapper_370.h"
#include "mappers/mapper_372.h"
#include "mappers/mapper_374.h"
#include "mappers/mapper_375.h"
#include "mappers/mapper_377.h"
#include "mappers/mapper_380.h"
#include "mappers/mapper_381.h"
#include "mappers/mapper_382.h"
#include "mappers/mapper_384.h"
#include "mappers/mapper_389.h"
#include "mappers/mapper_393.h"
#include "mappers/mapper_394.h"
#include "mappers/mapper_395.h"
#include "mappers/mapper_396.h"
#include "mappers/mapper_398.h"
#include "mappers/mapper_399.h"
#include "mappers/mapper_400.h"
#include "mappers/mapper_401.h"
#include "mappers/mapper_403.h"
#include "mappers/mapper_404.h"
#include "mappers/mapper_406.h"
#include "mappers/mapper_409.h"
#include "mappers/mapper_410.h"
#include "mappers/mapper_411.h"
#include "mappers/mapper_412.h"
#include "mappers/mapper_413.h"
#include "mappers/mapper_414.h"
#include "mappers/mapper_415.h"
#include "mappers/mapper_416.h"
#include "mappers/mapper_417.h"
#include "mappers/mapper_420.h"
#include "mappers/mapper_428.h"
#include "mappers/mapper_429.h"
#include "mappers/mapper_431.h"
#include "mappers/mapper_432.h"
#include "mappers/mapper_433.h"
#include "mappers/mapper_434.h"
#include "mappers/mapper_436.h"
#include "mappers/mapper_437.h"
#include "mappers/mapper_442.h"
#include "mappers/mapper_446.h"
#include "mappers/mapper_447.h"
#include "mappers/mapper_451.h"
#include "mappers/mapper_452.h"
#include "mappers/mapper_455.h"
#include "mappers/mapper_456.h"
#include "mappers/mapper_457.h"
#include "mappers/mapper_471.h"
#include "mappers/mapper_512.h"
#include "mappers/mapper_513.h"
#include "mappers/mapper_516.h"
#include "mappers/mapper_518.h"
#include "mappers/mapper_524.h"
#include "mappers/mapper_527.h"
#include "mappers/mapper_528.h"
#include "mappers/mapper_529.h"
#include "mappers/mapper_530.h"
#include "mappers/mapper_532.h"
#include "mappers/mapper_538.h"
#include "mappers/mapper_539.h"
#include "mappers/mapper_541.h"
#include "mappers/mapper_543.h"
#include "mappers/mapper_547.h"
#include "mappers/mapper_550.h"
#include "mappers/mapper_554.h"
#include "mappers/mapper_556.h"
#include "mappers/mapper_557.h"
#include "mappers/mapper_558.h"
#include "mappers/mapper_559.h"
#include "mappers/mapper_560.h"
#include "mappers/mapper_Active.h"
#include "mappers/mapper_Agci.h"
#include "mappers/mapper_Ave.h"
#include "mappers/mapper_AxROM.h"
#include "mappers/mapper_Bandai.h"
#include "mappers/mapper_BMCFK23C.h"
#include "mappers/mapper_BxROM.h"
#include "mappers/mapper_Caltron.h"
#include "mappers/mapper_Camerica.h"
#include "mappers/mapper_CNROM.h"
#include "mappers/mapper_ColorDreams.h"
#include "mappers/mapper_Coolboy.h"
#include "mappers/mapper_CPROM.h"
#include "mappers/mapper_FDS.h"
#include "mappers/mapper_FFESMC.h"
#include "mappers/mapper_FS304.h"
#include "mappers/mapper_GameGenie.h"
#include "mappers/mapper_GxROM.h"
#include "mappers/mapper_Hen.h"
#include "mappers/mapper_Hes.h"
#include "mappers/mapper_Irem.h"
#include "mappers/mapper_Jaleco.h"
#include "mappers/mapper_JYASIC.h"
#include "mappers/mapper_Kaiser.h"
#include "mappers/mapper_Magic.h"
#include "mappers/mapper_MMC3_old.h"
#include "mappers/mapper_MMC5.h"
#include "mappers/mapper_Ntdec.h"
#include "mappers/mapper_Rcm.h"
#include "mappers/mapper_Rex.h"
#include "mappers/mapper_Sachen.h"
#include "mappers/mapper_SC_127.h"
#include "mappers/mapper_Taito.h"
#include "mappers/mapper_Tengen.h"
#include "mappers/mapper_Txc.h"
#include "mappers/mapper_TxROM.h"
#include "mappers/mapper_UxROM.h"
#include "mappers/mapper_VRC1.h"
#include "mappers/mapper_VRC3.h"
#include "mappers/mapper_Vs.h"
// UNIF
#include "mappers/mapper_891227.h"
#include "mappers/mapper_A65AS.h"
#include "mappers/mapper_BJ56.h"
#include "mappers/mapper_BMC64IN1NOREPEAT.h"
#include "mappers/mapper_BMC70IN1.h"
#include "mappers/mapper_BMC810544CA1.h"
#include "mappers/mapper_BMC830425C.h"
#include "mappers/mapper_BMCNTD03.h"
#include "mappers/mapper_BMCG146.h"
#include "mappers/mapper_BMCHP898F.h"
#include "mappers/mapper_BOY.h"
#include "mappers/mapper_BS5.h"
#include "mappers/mapper_CC_21.h"
#include "mappers/mapper_Coolgirl.h"
#include "mappers/mapper_CTC09.h"
#include "mappers/mapper_DREAMTECH01.h"
#include "mappers/mapper_DRIPGAME.h"
#include "mappers/mapper_EDU2000.h"
#include "mappers/mapper_EH8813A.h"
#include "mappers/mapper_FARIDUNROM8IN1.h"
#include "mappers/mapper_GS_20xx.h"
#include "mappers/mapper_K3036.h"
#include "mappers/mapper_K3046.h"
#include "mappers/mapper_K3071.h"
#include "mappers/mapper_KS106C.h"
#include "mappers/mapper_KS7012.h"
#include "mappers/mapper_KS7013B.h"
#include "mappers/mapper_KS7016.h"
#include "mappers/mapper_KS7017.h"
#include "mappers/mapper_KS7021A.h"
#include "mappers/mapper_KS7030.h"
#include "mappers/mapper_KS7031.h"
#include "mappers/mapper_KS7032.h"
#include "mappers/mapper_LH10.h"
#include "mappers/mapper_LH32.h"
#include "mappers/mapper_LH51.h"
#include "mappers/mapper_Malee.h"
#include "mappers/mapper_RESETNROMXIN1.h"
#include "mappers/mapper_RT_01.h"
#include "mappers/mapper_SA005A.h"
#include "mappers/mapper_T262.h"
#include "mappers/mapper_TJ03.h"
#include "mappers/mapper_UNIF8157.h"
#include "mappers/mapper_UNIFSMB2J.h"
#include "mappers/mapper_WS.h"
#include "mappers/mapper_YOKO.h"

#include "mappers/FME7.h"
#include "mappers/N118.h"
#include "mappers/MMC1.h"
#include "mappers/MMC2.h"
#include "mappers/MMC3.h"
#include "mappers/MMC4.h"
#include "mappers/VRC2and4.h"
#include "mappers/VRC6.h"
#include "mappers/VRC7.h"

#define _control_bank(val, max)	if ((val) > (max)) (val) &= (max);
#define control_bank(max) _control_bank(value, max)
#define _control_bank_with_AND(val, mask, max) (val) &= (mask); _control_bank(val, max)
#define control_bank_with_AND(mask, max) _control_bank_with_AND(value, mask, max)
#define prg_rom_rd(address) prg.rom_8k[((address) >> 13) & 0x03][(address) & 0x1FFF]

enum mappers_op_battery { RD_BAT, WR_BAT };

typedef struct _mapper {
	BYTE mirroring;
	BYTE write_vram;
	WORD rom_map_to[4];
	BYTE *internal_struct[10];
	WORD internal_struct_size[10];
	BYTE trainer[512];
	struct _misc_roms {
		size_t size;
		BYTE *data;
	} misc_roms;
} _mapper;

extern _mapper mapper;

BYTE map_init(void);
void map_quit(void);
BYTE map_prg_malloc(size_t size, BYTE set_value, BYTE init_chip0_rom);
void map_prg_rom_8k(BYTE banks_8k, BYTE at, WORD value);
void map_prg_rom_8k_reset(void);
void map_prg_rom_8k_update(void);
void map_prg_ram_init(void);
BYTE map_prg_ram_malloc(WORD size);
void map_prg_ram_memset(void);
void map_prg_ram_battery_save(void);
void map_prg_ram_battery_load(void);
BYTE map_chr_malloc(size_t size, BYTE set_value, BYTE init_chip0_rom);
void map_chr_bank_1k_reset(void);
BYTE map_chr_ram_init(void);
BYTE map_chr_ram_extra_init(uint32_t size);
void map_chr_ram_extra_reset(void);
BYTE map_chr_ram_slot_in_range(BYTE slot);
BYTE map_misc_malloc(size_t size, BYTE set_value);
void map_set_banks_max_prg(void);
void map_set_banks_max_chr(void);
void map_bat_wr_default(FILE *fp) ;
void map_bat_rd_default(FILE *fp);

void map_chr_rom_1k(const WORD address, const WORD value);
void map_chr_rom_2k(const WORD address, const WORD value);
void map_chr_rom_4k(const WORD address, const WORD value);
void map_chr_rom_8k(const WORD value);

void map_nmt_1k(BYTE slot, const WORD value);
void map_nmt_chr_ram_1k(BYTE slot, const WORD value);
void map_nmt_chr_rom_1k(BYTE slot, const WORD value);
void map_nmt_chr_rom_2k(BYTE slot, const WORD value);
void map_nmt_chr_rom_4k(const WORD value);

#endif /* MAPPERS_H_ */
