SRCS=\
 ../../../myWindows/myAddExeFlag.cpp \
 ../../../myWindows/mySplitCommandLine.cpp \
 ../../../myWindows/wine_date_and_time.cpp \
 \
 ../../UI/Console/ConsoleClose.cpp \
 ../../UI/Console/ExtractCallbackConsole.cpp \
 ../../UI/Console/BenchCon.cpp \
 ../../UI/Console/List.cpp \
 ../../UI/Console/Main.cpp \
 ../../UI/Console/MainAr.cpp \
 ../../UI/Console/OpenCallbackConsole.cpp \
 ../../UI/Console/PercentPrinter.cpp \
 ../../UI/Console/UpdateCallbackConsole.cpp \
 ../../UI/Console/UserInputUtils.cpp \
 \
 ../../../Common/CommandLineParser.cpp \
 ../../../Common/CRC.cpp \
 ../../../Common/IntToString.cpp \
 ../../../Common/ListFileUtils.cpp \
 ../../../Common/StdInStream.cpp \
 ../../../Common/StdOutStream.cpp \
 ../../../Common/MyString.cpp \
 ../../../Common/MyWindows.cpp \
 ../../../Common/StringConvert.cpp \
 ../../../Common/StringToInt.cpp \
 ../../../Common/UTFConvert.cpp \
 ../../../Common/MyVector.cpp \
 ../../../Common/Wildcard.cpp \
 \
 ../../../Windows/DLL.cpp \
 ../../../Windows/Error.cpp \
 ../../../Windows/FileDir.cpp \
 ../../../Windows/FileFind.cpp \
 ../../../Windows/FileIO.cpp \
 ../../../Windows/FileName.cpp \
 ../../../Windows/PropVariant.cpp \
 ../../../Windows/PropVariantConversions.cpp \
 ../../../Windows/System.cpp \
 ../../../Windows/Time.cpp \
 \
 ../../Common/CreateCoder.cpp \
 ../../Common/FilePathAutoRename.cpp \
 ../../Common/FileStreams.cpp \
 ../../Common/FilterCoder.cpp \
 ../../Common/ProgressUtils.cpp \
 ../../Common/StreamUtils.cpp \
 \
 ../../UI/Common/ArchiveCommandLine.cpp \
 ../../UI/Common/ArchiveExtractCallback.cpp \
 ../../UI/Common/ArchiveOpenCallback.cpp \
 ../../UI/Common/DefaultName.cpp \
 ../../UI/Common/EnumDirItems.cpp \
 ../../UI/Common/Extract.cpp \
 ../../UI/Common/ExtractingFilePath.cpp \
 ../../UI/Common/Bench.cpp \
 ../../UI/Common/LoadCodecs.cpp \
 ../../UI/Common/OpenArchive.cpp \
 ../../UI/Common/PropIDUtils.cpp \
 ../../UI/Common/SetProperties.cpp \
 ../../UI/Common/SortUtils.cpp \
 ../../UI/Common/TempFiles.cpp \
 ../../UI/Common/Update.cpp \
 ../../UI/Common/UpdateAction.cpp \
 ../../UI/Common/UpdateCallback.cpp \
 ../../UI/Common/UpdatePair.cpp \
 ../../UI/Common/UpdateProduce.cpp \
 \
 ../../Archive/Common/OutStreamWithCRC.cpp 



SRCS_C=\
 ../../../../C/Alloc.c \
 ../../../../C/Threads.c \

include ../../../../makefile.rules

Main.o : ../../UI/Console/Main.cpp
	$(CXX) $(CXXFLAGS) ../../UI/Console/Main.cpp

